### ISSUE TITLE
Feature: pass the mouse click event to pty

### ISSUE THREAD

**Issue by jaeheonji** [zellij-org/zellij#1013]
This feature related to #1011 

In the `tab`, mouse click events are only used for pane selection (focus)

https://github.com/zellij-org/zellij/blob/ddbf16e1b30dba87f76d34b2ad52dcf869bb00be/zellij-server/src/tab/mod.rs#L1834-L1850

This means that programs that use a mouse in the TUI environment (eg neovim) will ignore mouse event.

It looks like we need to some logic to pass the mouse click event to pty after selecting the pane.

**Comment by a-kenji** [comment]
Here is some prior work, that could potentially be a good starting point for anyone wanting / having the ability to work on it:

 Sending mouse events to the terminal #624  .

**Comment by tlinford** [comment]
#624 looks like a great start, the major thing i think it's missing is only sending mouse events to panes that have themselves enabled mouse mode. Info on that can be found here: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking.

Another thing that needs some thought is what modes should be supported, as far as I can tell SGR (1006) should be preferred.

**Comment by klamonte** [comment]
> Another thing that needs some thought is what modes should be supported, as far as I can tell SGR (1006) should be preferred.

SGR is the best for today, as it has no limit on coordinates and can distinguish between each button for all events.

UTF-8 (1005) is also good because it has a large range, but the button release event is a single event for any number of buttons.  If you do SGR or UTF-8 first, doing the next one might look confusing because there is a behavior difference in addition to an encoding difference.

Note that applications will often ask for several things at once like CSI ? 1002;1003;1005;1006h --> give me SGR any-event, if you don't have SGR make it UTF-8, if you don't have any-event make it button-event.

**Comment by imsnif** [comment]
I think this can be closed, right @tlinford ?

**Comment by tlinford** [comment]
Yep, support for SGR was added in #1191, I'd say that if we want to add support for other encodings we can open new, specific, issues for that.
