### ISSUE TITLE
Allow for more fine-grained styling/theming

### ISSUE THREAD

**Issue by mainrs** [zellij-org/zellij#1027]
For example, the `status-bar` plugin has fixed styles. It always uses the same color names for the same elements. Theming is supported, but only to some degree of freedom.

It would be great (as mentioned in the code of the plugin) if one could freely set the colors for the parts of the UI. The powerline-like shortcut highlights are always black text on fg color. And sometimes this isn't easy to work with with themes.

**Comment by mainrs** [comment]
Hey @a-kenji , thanks for answering! Are there already plans on how that interface might look like?

**Comment by a-kenji** [comment]
Yes, but not that specifically, because we do plan on possibly switching away from yaml.

It will in essence be a hashmap, so that plugins can support nested configurations.

I imagine in this particular instance the default would be the different elements having our style associated with it and people having the ability to customize that.

For example something along the lines of:
```
active_tab: fg
inactive_tab: bg
```
and it can be configured to 
```
active_tab: 0
inactive_tab: fg
```

**Comment by JCallicoat** [comment]
@a-kenji Is this the PR for plugin configuration https://github.com/zellij-org/zellij/pull/754 ? It seems like activity has stalled there.

Would it be feasible to to have a narrower scope to solve the color configuration issue here, where zellij just directly passes a theme to the plugin at init without getting into the issue of arbitrary user configuration being passed to the plugins? Then users could at least configure plugin colors via the theme. I haven't looked much into the plugin system so no idea if that could work or if it would be just as much work as passing arbitrary config, so apologies if it's a silly question or has been addressed before.
