### ISSUE TITLE
Backspace triggers move action (ctrl + h)

### ISSUE THREAD

**Issue by matmoscicki** [zellij-org/zellij#1031]
**Basic information**

`zellij --version`: zellij 0.24.0
`tput lines`: 80
`tput cols`: 305
`uname -av`: Linux VirtualBox 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Further information**

When I want to delete the last typed character using backspace, zellij goes into panel move mode, as if I pressed ctrl +h.
I have default configuration.

**Comment by raphCode** [comment]
For me, I actually only see this triggering with `Ctrl + backspace`.

Bash or vim without zellij do the same, `Ctrl + backspace` and `Ctrl + h` both behave like `backspace`.

I think this is a "feature" of my terminal emulator (alacritty):
I played around with `stty erase x` to set the tty's line discipline erase key to `x`. After that, raw mode applications display `^?` for normal backspace and `^H` for Ctrl + backspace...

In fact, [this](http://www.linusakesson.net/programming/tty/) mentions that backspace is usually bound to `^?` or `^H`, depending on the terminal emulator.

**Comment by matmoscicki** [comment]
Thank you!
MobaXterm sends `^H` as backspace. I disabled this option and it works as should :)

**Comment by raphCode** [comment]
Should we close this issue?
There seems not much that can be done on zellij side.

**Comment by Dhamma-valence** [comment]
This seems to still be happening, I'm on master. I thought it was alacritty causing it, (and it was as well as messing up `Home` and `End`, but after reverting to `v0.10.1` it went away on plain alacritty without zellij, yet still happens when alacritty is used with zellij.

I use ctrl+backspace to kill-by-word which speeds up editing and typing significantly, and won't be able to comfortably use this otherwise lovely software with it. I wish I had a better grasp of what's causing this, all I know is that `ctrl + h` and `ctrl + bksp` were once the same ANSI escape code, and now we use them separately but some terminal emulators sometimes make them the same, it seems.

**Comment by raphCode** [comment]
> but after reverting to `v0.10.1` it went away on plain alacritty without zellij, yet still happens when alacritty is used with zellij.

What "went away" / "still happens"? Without zellij, there is no move action that can be triggered, which is what this issue is about.

> I wish I had a better grasp of what's causing this

I can recommend http://www.linusakesson.net/programming/tty/
When you press a key, it depends on the terminal emulator (and its config) which ansi escape codes are sent, and what happens depends either on the terminal settings (when line discipline is active), or the specific application setting (terminal in raw mode).

**Comment by franalbani** [comment]
I solved it (at least in `coolretroterm`) by commenting in this way:

```console
$ grep -n -C 1 'Ctrl h' .config/zellij/config.kdl
40-    move {
41:        // bind "Ctrl h" { SwitchToMode "Normal"; }
42-        bind "n" "Tab" { MovePane; }
--
180-    // shared_except "move" "locked" {
181:    //     bind "Ctrl h" { SwitchToMode "Move"; }
182-    // }
```

**Comment by cyberalt1** [comment]
Please reopen, this is the single largest issue with zellij rn and no comment here provided a solution to it

**Comment by Jimvancouver666** [comment]
I have same issue. I have tried all solution in this thread, none works.

**Comment by guysrd** [comment]
is there any fix for this issue?

**Comment by Myriade-Medieval** [comment]
@cyberalt1 @guysrd This is an issue specific to your terminal emulator. Zellij can't do anything about it as it receives [^H](https://en.wikipedia.org/wiki/Backspace#^H) when you press backspace which is the same as ctrl H, instead of [^?](https://en.wikipedia.org/wiki/Delete_character). More than an issue, it's a choice of standards I believe, and you can probably configure this in the terminal emulator's settings (konsole, alacritty, kitty, ghostty etc...)
