### ISSUE TITLE
Text copying not working

### ISSUE THREAD

**Issue by matmoscicki** [zellij-org/zellij#1033]
**Basic information**

`zellij --version`: zellij 0.24.0
`tput lines`: 65
`tput cols`: 207
`uname -av` or `ver`(Windows): Linux szary-VirtualBox 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`mobaXterm v21.5`

**Further information**
Copying text does not work as I would expect. After selecting, I get a message that the text was copied, but pasting with Shift+Insert pastes me what was previously in the clipboard. ( https://gifyu.com/image/Sb1ae ).
It may be related to some mobaXterm settings, but it does not work only in Zellij (tmux has no problem).

**Comment by jaeheonji** [comment]
Hi, @matmoscicki!

I saw the GIF you uploaded. First of all, I am not a user of `mobaXterm`, so this may not be the correct answer.
Maybe, this is due to the difference between the `PRIMARY selection` and the `clipboard`.

From the GIF view, it looks like you are using the `copy-on-select` feature in `mobaXterm` .  And probably, the data copied through this feature goes to `PRIMARY selection`.

zellij has its own `copy-on-select` feature, which only copies data to the `clipboard`. (For reference, we are currently developing a function to support various clipboards. #1022)

Perhaps the data pasted through `Shift+Insert` in `mobaXterm` comes from `PRIMARY selection`.

**Comment by tlinford** [comment]
@matmoscicki it could be that `mobaXterm` does not support the osc52 instruction we use by default to handle copying. This can be worked around in a couple of ways:

- disable mouse mode completely
- select text with shift + mouse

**Comment by a-kenji** [comment]
This should be addressed now.
