### ISSUE TITLE
Faster way or conveniences for attaching to session by name

### ISSUE THREAD

**Issue by colemickens** [zellij-org/zellij#1169]
Hi,

It looks like clap does not *yet* support runtime-provided completion support (https://github.com/clap-rs/clap/issues/1232), hence I'm not sure there's an easy path to providing completion for session names.

However, attaching to a session implies that someone is loading the entire zellij UI interactive inactively anyway.

What if `zellij attach` or `zellij attach -m` offered an interactive menu for the user to select a session?

Alternatively, would it be possible to allow `zellij attach f` to match a session named `foobar-awesome`, assuming there are no other sessions starting with `f` ?

I guess one last no-zellij-change-needed option would be to setup some sort of shell keybind so that I could pipe `zellij list-sessions` into `skim` or something? Does someone else have something they like for this?

**Comment by a-kenji** [comment]
Hey! Thank you for taking the time for opening this issue.

>hence I'm not sure there's an easy path to providing completion for session names. 

There is sadly not, but we could append functions to the completions.
The negative here would be that this is very shell dependent, but it could be reasonable to support the shells as good as we can.
There is an issue that has a great example: #1030


> What if `zellij attach` or `zellij attach -m` offered an interactive menu for the user to select a session?

That would be awesome, I think connecting to your last point, maybe we could even support fzf/skim and family choosers similarly.
That way the maintenance burden would be not as high with still full functionality.

> Alternatively, would it be possible to allow `zellij attach f` to match a session named `foobar-awesome`, assuming there are no other sessions starting with `f` ?

So, that is another possibly good idea. Just for the first letter, and maybe restrict the possibility of automatically generating the same first letter, in order to make this functionality more useful.

> I guess one last no-zellij-change-needed option would be to setup some sort of shell keybind so that I could pipe `zellij list-sessions` into `skim` or something? Does someone else have something they like for this?

In my window manager I have bound something similar to this
(I have removed some very specific integration I use):
```
#!/usr/bin/env bash

ZJ_SESSIONS=$(zellij list-sessions)
NO_SESSIONS=$(echo "${ZJ_SESSIONS}" | wc -l)
TERMINAL=alacritty

if [ "${NO_SESSIONS}" -ge 2 ]; then
    "${TERMINAL}" -e zellij attach \
    "$(echo "${ZJ_SESSIONS}" | rofi -dmenu -l "${NO_SESSIONS}")"
else
   "${TERMINAL}" -e zellij attach -c
fi
```
But you can also remove the terminal and use it from an already
existing terminal:
```
#!/usr/bin/env bash

ZJ_SESSIONS=$(zellij list-sessions)
NO_SESSION=$(echo "${ZJ_SESSIONS}" | wc -l)

zellij attach 1>/dev/null || \
    zellij attach \
    "$(echo "${ZJ_SESSIONS}" | rofi -dmenu -l "${NO_SESSION}")"
```
and switch it with skim:
```
#!/usr/bin/env bash
ZJ_SESSIONS=$(zellij list-sessions)
NO_SESSIONS=$(echo "${ZJ_SESSIONS}" | wc -l)

if [ "${NO_SESSIONS}" -ge 2 ]; then
    zellij attach \
    "$(echo "${ZJ_SESSIONS}" | sk)"
else
   zellij attach -c
fi
```

**Comment by a-kenji** [comment]
This is now implemented!
