### ISSUE TITLE
How to disable copy on selection and change the color of selection?

### ISSUE THREAD

**Issue by SHiftLin** [zellij-org/zellij#1192]
Can I disable copy-on-selection without disabling the mouse mode in zellij? Besides, how can I change the color of selection?

Thanks

**Comment by jaeheonji** [comment]
> Can I disable copy-on-selection without disabling the mouse mode in zellij?

Unfortunately, not currently. However, it seems like a good idea to make the `copy_on_selection` mode optional.

> how can I change the color of selection?

You can change it by using the [theme](https://zellij.dev/documentation/themes.html). But, since this is changing the whole theme, so only the "selection" color cannot be changed.

**Comment by SHiftLin** [comment]
Thanks for your reply! I think it is useful to make the copy_on_selection mode optional

**Comment by a-kenji** [comment]
> Can I disable copy-on-selection without disabling the mouse mode in zellij? Besides, how can I change the color of selection?
> 
> Thanks

Not directly, but you can turn off that it takes over your
clipboard as described here: #1065.

> # Provide a command to execute when copying text. The text will be piped to
# the stdin of the program to perform the copy. This can be used with
# terminal emulators which do not support the OSC 52 ANSI control sequence
# that will be used by default if this option is not set.
# Examples:
#copy_command: "xclip -selection clipboard" # x11
#copy_command: "wl-copy"                    # wayland
#copy_command: "pbcopy"                     # osx

# Choose the destination for copied text
# Allows using the primary selection buffer (on x11/wayland) instead of the system clipboard.
# Does not apply when using copy_command.
# Options:
#   - system (default)
#   - primary
# copy_clipboard: primary

You can change this to a NoOp operation to not accidentally overwrite your clipboard.

Also pressing `SHIFT` is bypassing the selection of `zellij` and passing it through.

> I think it is useful to make the copy_on_selection mode optional

I agree!

**Comment by tlinford** [comment]
Just to be clear, @SHiftLin would you want the selection to be not be copied on release, but be able to copy explicitly with a keybinding?

**Comment by SHiftLin** [comment]
@tlinford Yes, I would prefer to copy only when I press cmd+c or ctrl+c.

**Comment by tlinford** [comment]
that should be coming pretty soon!

**Comment by SHiftLin** [comment]
Thanks for the amazing fast reply!

**Comment by steakhutzeee** [comment]
Hi, while selecting text with mouse works outside of Zellij, it works but is “invisible” in Zellij. I can of course use Shift and then select but at that point I can’t just copy with a custom key binding. Any idea why Zellij own mouse selection is invisible.

To be clear, I am actually able to copy the selected text, it’s just that the selection is invisible for some reason. Shift select works fine and is visible instead.
