### ISSUE TITLE
Pasting in vim broken in v0.26.0

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1219]
Pasting in vim is broken for me since zellij v0.26.0 in alacritty:
Before the update, I could enter insert mode and paste via `shift+click` or `ctrl+shift+V` to insert some text.
Now every character is interpreted like I am in normal mode, meaning that I run some vim commands based on the clipboard content, messing up my document.

I do not know what is going on, `:set paste` didn't change anything inside vim.

It there a workaround to revert to the v0.25.0 behavior?

Other issues where something changed in the clipboard behavior:
https://github.com/zellij-org/zellij/issues/1216
https://github.com/zellij-org/zellij/issues/1218

**Comment by raphCode** [comment]
> try doing: `set mouse=a` and `set ttymouse=sgr`?

Sadly didn't change anything. I even tried with `vim -u NONE` to eliminate effects from `.vimrc` files.

**Comment by imsnif** [comment]
Right, I'll take a look this week. Meanwhile I'm afraid the best workaround I have is to downgrade to 0.25.0. Sorry about that!

**Comment by imsnif** [comment]
Hey @raphCode - nice troubleshooting on this!

Zellij itself operates in bracketed paste mode (so that for example, if you paste a large chunk of text - parts of which can be interpreted as Zellij commands - it will interpret it as text rather than commands). So what it does is track which terminal pane is itself in bracketed paste mode and only sends the bracketed paste signals to those with the mode enabled.

In a recent change, I revamped how we handle bracketed paste (namely, moved away from our self-cooked solution to use Termion) and accidentally broke the above process (we were still keeping track of which pane was in bracketed paste mode, but not stripping the bracketed paste start/end sequence correctly - meaning that all panes were getting these instructions regardless of whether they asked for them or not).

I just issued a hotfix for this in main - would you care to test it out and make sure it solves the problem for you before I release a patch?

**Comment by raphCode** [comment]
I can confirm this works again!

---

I tried:
- Starting vim normally, this means `TERM=alacritty` and vim signals no bracketed paste support:
  - pasting in insert mode works again! no escape codes going haywire
  - pasting in normal mode does the expected command-thing
- `:set term=xterm-256color`: vim switches to bracketed paste support
  - pasting in normal or insert mode does the right thing, test is inserted, no vim commands are executed

**Comment by imsnif** [comment]
Released a fix in 0.26.1
