### ISSUE TITLE
SSH key passphrase is not remembered after starting zellij

### ISSUE THREAD

**Issue by DannyBen** [zellij-org/zellij#1319]
**Basic information**

`zellij --version`: `0.27.0`
`tput lines`: `33`
`tput cols`: `137`
`uname -av`: `Linux ubuntu-focal 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Further information**

SSH passphrase is not remembered inside zellij. The only related issue I found was #862, but it does not seem related.

**Reproduction steps**

1. Outside of zellij, run ssh-add (assuming your have a key with passphrase)
2. Type the passphrase
3. Enter zellij workspace
4. Run an ssh command 
5. Expected behavior: Passphrase is not requested, and the command succeeds
6. Actual behavior: Passphrase is requested

**Additional information**

When using tmux, I have this in my `~/.bashrc` to solve this problem:

```bash
# Passthrough the SSH agent to tmux panels
if tmux info &> /dev/null; then
  eval $(tmux show-env -s |grep '^SSH_')
fi
```

**Comment by raphCode** [comment]
How do you start ssh-agent? Do you have something related to it in your `.bashrc`?

**Comment by DannyBen** [comment]
> How do you start ssh-agent? Do you have something related to it in your `.bashrc`?

Yes, of course - sorry. The usual (I think): `eval $(ssh-agent) > /dev/null`

**Comment by raphCode** [comment]
I think this is the culprit: a new ssh-agent instance is started for every shell you open, and they are all independent, meaning you must add all your keys to each agent individually.

This is not a zellij bug, it should happen every time when you start a new shell. Try executing `bash` or opening a new terminal window in step 3 of your reproduction guide.

I guess the reason it works in tmux is because the code snippet from your first post comes after starting a new ssh-agent, overwriting the environment variables so that `ssh` now connects to the ssh-agent started from outside tmux.

A more portable solution would be to detect that a ssh-agent is already running and re-connecting to that instance. Have a look at `keychain` which can do exactly that.

**Comment by DannyBen** [comment]
I will try with keychain, although this approach I am currently using has served me well for years (and opening any subshell does not require the passphrase again).

**Comment by DannyBen** [comment]
keychain works nicely, thanks for the tip. I will close this ticket.
