### ISSUE TITLE
Error when trying to attach by index

### ISSUE THREAD

**Issue by fpauser** [zellij-org/zellij#1339]
OS info:
```
~$ uname -av
Linux fpx-desktop 5.16.20-200.fc35.x86_64 #1 SMP PREEMPT Wed Apr 13 22:09:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Zellij version:

```
~$ cargo version
cargo 1.60.0 (d1fd9fe 2022-03-01)
~$ zellij --version
zellij 0.28.1
```

I have these running sessions:

```
~$ zellij ls
marvelous-sleep (current)
clever-copy
shy-window
```

Trying to attach to the first session by index gives an error:
```
~$ zellij attach --index 0
Error occurred: creation time is not available for the filesystem
```

I am using btrfs - seems like there is some issue with rust + btrfs?

**Comment by jaeheonji** [comment]
Good find! I'm getting the same error in my environment (WSL). This seems to be a bug.
I'll check it out! thanks :)

**Comment by imsnif** [comment]
@jaeheonji - do you have an idea for a quick workaround for this?

**Comment by jaeheonji** [comment]
@imsnif - Yep, for now I'm going to use modification time (mtime) instead of creation time.

I did some tests. it seems possible for the following reasons.
* After the session file is created, it cannot be modified.
* Compared to `ctime` and `atime`, `mtime` is commonly used in most filesystems.
  * ctime may change due to inodes.
  * atime may have cases such as `noatime`. 

At this point, I think this is the easy and reasonable solution.

**Comment by imsnif** [comment]
Sounds good @jaeheonji ! I want to release a version at the beginning of next week. Do you think you can get the fix merged by then?

**Comment by jaeheonji** [comment]
Yes, it is possible!. I expect to process it in 2-3 days.
