### ISSUE TITLE
Crash when catting random bytes

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1346]
While filing #1345, I reliably got some crashes on zellij v0.28.1.
Do a `cat /dev/urandom` inside zellij, after some seconds to minutes I hit:
```
Error occurred in server:

  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │   	1. screen_thread: HandlePtyBytes
  │
  ├─▶ At zellij-server/src/panes/grid.rs:1543:46
  ╰─▶ index out of bounds: the len is 1 but the index is 1
  ```

**Comment by imsnif** [comment]
Yeah, both this and #1345 are regressions unfortunately. I used to do exactly these sorts of tests in the early days :)
I'll do another round this week to patch things up and hopefully soon we'll add some proper error handling there so that even if this happens, at worst the specific terminal pane will glitch a little.
