### ISSUE TITLE
Consider merging --layout and --layout-path

### ISSUE THREAD

**Issue by bigbass1997** [zellij-org/zellij#1412]
When trying to use layouts for the first time and reading through the docs, I missed the distinction between these two arguments. I had tried to use `--layout` with a specific path which I knew pointed to a valid layout file. Thinking this must be a bug, I looked through Github and Discord. On Discord I found someone else had also run into the same issue.

Worse, the error message for `--layout` made me think that it simply couldn't find the file, as if there was a permission problem or a spelling error. Additionally, if you happen to use an absolute path with `--layout` then it works, only adding to the confusion.

My understanding is that there used to only be one argument, and that `--layout-path` was made after #322 brought up a very specific situation which resulted in unexpected behavior when no argument was used. It seems to me the only reason to have two arguments is to make a distinction between a path relative to the current directory, vs a path relative to the layout-dir. But I'm not sure why this distinction is necessary.

If others feel it best to keep them both, then I'd like to at least see the error message improved to assist users. There are a few possible solutions:
* Change `--layout`'s IoError to specify the absolute path it attempted to search for the file. (hints to the user that it's expecting a path relative to layout-dir)
* Add a suggestion to both `--layout` and `layout-path`'s IoErrors to try using the opposite argument. (e.g. instead of `IoError: The layout was not found, File: {}`, use `IoError: The layout was not found. Did you mean '--layout-path {}'?`, and vis-versa).
* The above, but only if zellij detects that it would have found a file if the user had used the opposite argument.

If others feel merging them again is best, then we'd need to decide which location gets priority when a relative path is used. Or else throw an error message if the same filename is found in both/multiple locations.

**Comment by imsnif** [comment]
I very much agree, and have myself gotten confused about this once or twice (even knowing there is a distinction and not immediately remembering what it is).

IMO we shouldn't ever want to load a path relative to the layout dir. It's always layouts directly inside it. So the distinction can be `zellij --layout ./strider` vs. `zellij --layout strider`.

@a-kenji - I'm tagging you here because I seem to remember you might have had different thoughts about this. Am I missing something? Do you think differently?

**Comment by a-kenji** [comment]
> zellij --layout ./strider vs. zellij --layout strider.

I think that is a somewhat reasonable solution.

I still would prefer the current path, because it is clearer:
```
    -l, --layout <LAYOUT>              Name of a layout file in the layout directory
        --layout-path <LAYOUT_PATH>    Path to a layout yaml file
```

The other distinction is very implicit and not as easily understandable to a user, I believe.

**Comment by imsnif** [comment]
Cool. So we're saying:

We'll merge these two into `--layout` which if given a bare name will load it from the layout folder, and if given a path will load it from the current location.

@bigbass1997 - would you like to implement this?

**Comment by bigbass1997** [comment]
> @bigbass1997 - would you like to implement this?
Probably not. I've looked over the relevant parts of the codebase, but I think implementing this is a bit out of my depth for this project. Thanks for asking though.

**Comment by SpyrosRoum** [comment]
I'd like to pick this up but can we expand a bit on what "a bare name" means?

For example is this good?
  * It's not an absolute path,
  * Doesn't start with `./`
  * Doesn't contain slashes anywhere else


So essentially it's a single word like `foo` or `bar`, while `foo/bar` wouldn't count as a "bare name"

**Comment by jaeheonji** [comment]
I'd like to share my personal opinion on this topic.

It may be a little different from the topic, but first, I agree with @a-kenji. Although the user may be a little uncomfortable, there is an advantage that the function is clear because the command is separated.

However, one of the things that causes confusion personally seems to be the internal logic of `--layout-path`.

The `--layout-path` basically expects to receive the **actual path**, but if the path is incorrect, it searches for the path of the default layout.

I think `--layout-path` must only receive path input, and if the file does not exist or the format is wrong, zellij must output an error and exit.

In the case of `--layout`, it would be better to receive only the name of the layout. And if the name of the layout is not found in the `LAYOUT` folder, it would be more natural to run the default logic.

**Comment by jaeheonji** [comment]
@imsnif I'm sorry I'm confused about one thing. In the case of overridng, I fixed it myself last time 😅. So there is no problem at the moment.

Anyway, let me make a clear distinction between the topics.

1. One of the things I'm confused about is. These are the following cases:
```bash
$ ls projects/default.yaml
projects/default.yaml

# It works
$ zellij --layout-path projects/default/
# It works
$ cd projects && zellij --layout-path default
# It works. but in this case loaded the default layout
$ zellij --layout default
```

This experience makes me feel a little strange. My point is, if the two commands have to be separated, `--layout-path` should be received an extension. Or it should be clear to suggest that it is a path, such as `./some/path/layout.yaml` or `some_folder/layout.yaml`.

2. If not for these conditions, it may be better to combine the two commands.

But in this case, as @SpyrosRoum mentioned. Conditions will have to be clearer. Also, the order of processing will be important.

For example, is `zelij --layout default/` a layout that exists in the `LAYOUT` folder? Or is it the `default.yaml` that exists in the current folder? If that's not the case, do I need an error because the target is a **folder**? Or should I run zellij as the default layout?

If these things become clear, I think the two commands can be combined.

**Comment by SpyrosRoum** [comment]
Would it make sense to actually remove one of the two options all together? 
Allowing either just for a path or just for things in the `LAYOUT` dir would eliminate this debate all-together and make it simpler (imo).

Another option could be to first try and open it as a relative path and if that doesn't work try it as a relative path to the `LAYOUT` dir (or the other way around).

Lastly, we *could* keep it as separate commands but with better docs/errors.

**Comment by imsnif** [comment]
@jaeheonji - I understand what you're saying. The model I have in mind is similar to what most shells do today when executing a file. You have to explicitly specify a path (or a prefixed `./`) for it not to load the file from your `PATH`.

@SpyrosRoum - We just have these two use cases... and both of them are being used. So I'm afraid it would be unfortunate to remove one of them.

Since this seems to be a bit of a contested topic, I think it might be good to solve it with a name-change and (as @SpyrosRoum suggests) with better docs and errors.

Specifically I suggest:
`--layout` is the more common case (or at least what users usually try first) - it will always take the layout from ea filesystem path (or an http(s) path once we support that).
`--configured-layout` will always take a layout from the configured folder

Both of them will also scan the other option in case they don't find a layout. So they can give an error message that looks something like this:

```
zellij --layout strider
Error: No layout named "strider" found in <current_path>. There is a configured layout by that same name. Did you mean zellij --configured-layout strider?
```

What does everyone think?

**Comment by jaeheonji** [comment]
If we should use a prefix, personally I think `file://` is more explict than `layouts://`. 
In fact, this is a little different from the original topic, but there are many ways to bring up `layouts` from the web.

This should be discussed as a different issue, but I think the same way as the `docker` or `helm`  is pretty good.

```bash
$ zellij repo list
NAME		URL
official		https://blah/blah.git

$ zellij repo add <NAME> <URL>

$ zellij --layout --repo <NAME>
```

**Comment by imsnif** [comment]
> If we should use a prefix, personally I think `file://` is more explict than `layouts://`

True - but much less user friendly considering most users who use this for the first time want to load a layout file they just created and don't know the whole options of the app.

@jaeheonji I'm happy to discuss loading layouts from the web in a different issue - maybe once we start considering adding this functionality?

To the issue at hand: let's move forward. I think a good go-between is what I mentioned earlier with `--layout` and `--configured-layout`. @SpyrosRoum - are you still up for implementing this?

**Comment by jaeheonji** [comment]
> True - but much less user friendly considering most users who use this for the first time want to load a layout file they just created and don't know the whole options of the app.

I agree. And typing the prefix in addition would be very tiring. 😫 

> I'm happy to discuss loading layouts from the web in a different issue - maybe once we start considering adding this functionality?

Great :) I will create an issue with a simple proposal soon.

**Comment by a-kenji** [comment]
> The model I have in mind is similar to what most shells do today when executing a file. You have to explicitly specify a path (or a prefixed `./`) for it not to load the file from your `PATH`.

I would prefer this ux, as opposed to the current opposed one. 

`zellij --layout layout` should not load from path and load from default locations
`zellij --layout ./layout.yml` loads from the path

I don't like the potential ambiguity of it, but this is still a much better solution than to not have `--layout` take the default locations at all.

**Comment by a-kenji** [comment]
> `--configured-layout` / `--layout` solution we discussed above which seems to be a go-between between all of our concerns

I see the merged `--layout` flag as a go-between between all of our concerns. 

I see the `--configured-layout` flag as a considerable downgrade to our current ux.

**Comment by jaeheonji** [comment]
> > > The model I have in mind is similar to what most shells do today when executing a file. You have to explicitly specify a path (or a prefixed `./`) for it not to load the file from your `PATH`.
> > 
> > 
> > I would prefer this ux, as opposed to the current opposed one.
> > `zellij --layout layout` should not load from path and load from default locations `zellij --layout ./layout.yml` loads from the path
> > I don't like the potential ambiguity of it, but this is still a much better solution than to not have `--layout` take the default locations at all.
> 
> @jaeheonji - what do you think of this solution? Can we agree on it? (if you really don't like it, let's go with the `--configured-layout` / `--layout` solution we discussed above which seems to be a go-between between all of our concerns.)

Cool, To me, it looks distinguished and good.

**Comment by imsnif** [comment]
Great! I'm happy we reached an agreement. :)

To reiterate, this is what we're doing (quoted from @a-kenji)

> `zellij --layout layout` should not load from path and load from default locations
> `zellij --layout ./layout.yml` loads from the path

@SpyrosRoum - thank you for being patient with us. Would you still like to implement this?

**Comment by SpyrosRoum** [comment]
No worries, I'd rather we come up with something we all like compared to having to re-implement it in a month.

I'll work on it later/over the weekend!
