### ISSUE TITLE
Fix: Clicking Tabs inside the `compact-bar`

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#1477]
The `compact-bar` interprets mouse clicks on tabs with an incorrect offset.

`zellij --version`: 0.31.0

**Comment by tshepang** [comment]
This does not work for me for some reason, but it does for normal layout. I am running latest main branch.

**Comment by tshepang** [comment]
Hm, maybe mine is a different issue, because clicking tabs does nothing. I am running latest main branch.

**Comment by imsnif** [comment]
@tshepang - I just tested with main and for me mouse-clicking works. We've got a bit of an involved build system, so it's important to make sure to go through it (in this case I'd probably opt for `cargo make install /path/to/my/executable`).

Otherwise, I'd generally recommend not running from main and instead using the latest release (from crates.io or your favorite package repository).

If this still happens, mind giving me a ping so we'll get to the bottom of this?
