### ISSUE TITLE
If `copy_on_select` is false, if you try to copy with Ctrl+C, it just makes a new prompt in the shell

### ISSUE THREAD

**Issue by DUOLabs333** [zellij-org/zellij#1494]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: `zellij 0.30.0`
`tput lines`: 12
`tput cols`: 111
`uname -av` or `ver`(Windows): `Linux system 5.18.1-1-aarch64-ARCH #1 SMP PREEMPT Wed Jun 1 19:34:45 MDT 2022 aarch64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`nvim --version`: NVIM v0.5.0-dev+1299-g1c2e504d5  (used the appimage release)
`alacritty --version`: alacritty 0.7.2 (5ac8060b)

**Further information**
Reproduction steps, noticeable behavior, related issues, etc
If you use Shift+Select, it works.

**Comment by tlinford** [comment]
If you set `copy_on_select` to false, you also need to bind the `Copy` action to a keyboard shortcut.

As a note, you probably shouldn't use `ctrl+c` because it normally is used to interrupt running processes.

If you have a look at the default config (can be dumped to file with `zellij setup --dump-config > default-config.yaml`), you'll see that there is a commented out example of doing this for normal and scroll mode:
```
  # uncomment this and adjust key if using copy_on_select=false
  # - action: [Copy: ]
  #   key: [ Alt: 'c']
```

Also, when you use shift+select, you bypass zellij's built in mouse support, and mouse events are handled directly by the terminal emulator. This can be fine, but for example won't give a very good experience if you have two panes side by side.

**Comment by a-kenji** [comment]
The docs are now merged. I am closing this for now.
