### ISSUE TITLE
"?" instead of arrows/icons

### ISSUE THREAD

**Issue by pbspbsingh** [zellij-org/zellij#1566]
I don't see icons/arrows in zellij, instead I see "?", please refer the screenshot attached.

**Basic information**
`zellij --version`: zellij 0.30.0
`stty size`: 41 162
`uname -av` or `ver`(Windows): Darwin pbsingh-macbookpro.roam.internal 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

<img width="1904" alt="Screen Shot 2022-07-06 at 6 29 23 PM" src="https://user-images.githubusercontent.com/7175265/177671375-7dca4260-7488-4f18-8cde-3766fa3595c8.png">

**Comment by a-kenji** [comment]
@pbspbsingh,
thank you for reaching out, this is most likely because you don't have fonts installed that can render these characters.

Here are some ways to mitigate that:
- run `zellij setup --check` and read the output
- https://zellij.dev/documentation/compatibility.html#the-status-bar-fonts-dont-render-correctly
- https://zellij.dev/documentation/faq.html#i-see-broken-characters-in-the-default-ui-how-can-i-fix-this
- start zellij with `zellij options --simplified-ui true`

**Comment by pbspbsingh** [comment]
@a-kenji thanks for the quick response. Indeed fonts were missing, for now I'm using simplified ui, which is damn good. 
Cheers.
