### ISSUE TITLE
Zellij completely overrides terminal's handling of left/right clicks

### ISSUE THREAD

**Issue by SohumB** [zellij-org/zellij#1593]
**Basic information**

`zellij --version`: 0.30.0
`stty size`: 50 211
`uname -av`: Linux dynast 5.18.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1 (2022-06-16) x86_64 GNU/Linux
`tilix --version`: 
```
Versions
	Tilix version: 1.9.5
	VTE version: 0.68
	GTK Version: 3.24.34

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```

This is probably related to zellij's mouse handling, but zellij seems to completely take over my mouse buttons for my terminal window. On tilix, for instance, I'm used to right click opening up a menu that lets me configure some things, and left click opening links, double left-click selecting text, etc. The complete lack of a menu on right click even felt like an obvious bug to me the first time I tried zellij.

It would be nice if I didn't have to choose whether to have zellij's or my terminal's mouse handling.

**Comment by imsnif** [comment]
Hey, while I understand the frustration of not having access to right-click in your situation - this is unfortunately necessary in order to support things such as highlighting and copying text with the mouse without also picking up the pane-frames.

Aside from completely disabling mouse support, you can temporarily get around this at run-time by holding down the shift key and then clicking with the mouse.
