### ISSUE TITLE
Probably incorrect calculation of tab length in tab-bar plugin

### ISSUE THREAD

**Issue by yinqian-au** [zellij-org/zellij#1603]
https://github.com/zellij-org/zellij/blob/9dc392e75b960f53b2b39bf40fca3eb912a91862/default-plugins/tab-bar/src/tab.rs#L46-L47

**Comment by imsnif** [comment]
How so?

**Comment by imsnif** [comment]
Hmm... does it still happen in main?

**Comment by yinqian-au** [comment]
Sure, saddly.

**Comment by imsnif** [comment]
It could definitely be that this calculation is wrong. If you change it, is it fixed?

**Comment by yinqian-au** [comment]
`let mut tab_text_len = text.width() + (separator_width * 2) + 2;` fixes 99% of the problem. It doesn't work only when you click the first character of a tab.

**Comment by prscoelho** [comment]
Yeah, the correct length should be 2 (start space, end space, always constant) + 2 * separator_width. You can tell the length isn't correct in simplified ui since the algorithm that tries to fit in tabs breaks at certain points.

![screenshot-2022-08-05 00:26:02+01:00](https://user-images.githubusercontent.com/9609090/182971814-14f41649-2442-4a6a-a5ac-c7ace367fca6.png)

**Comment by prscoelho** [comment]
And yeah the first separator doesn't seem to trigger a tab switch, but that happens regardless of length since it's the 0th char. Probably a off by one error in the code that switches tab based on which mouse position.
