### ISSUE TITLE
macos terminal copy text didn't actually copied data to clipboard

### ISSUE THREAD

**Issue by jinfagang** [zellij-org/zellij#1662]
macos terminal copy text didn't actually copied data to clipboard

**Comment by imsnif** [comment]
Hey @jinfagang - I think the macos terminal doesn't support OSC52, which is the method we use in order to tell it to copy to your clipboard.

There's a workaround you can use which is to use an external command in order to copy. You'll need to install the relevant command for your mac (I think for macos it's `pbcopy`) and then adjust the Zellij config.

More info here: https://zellij.dev/documentation/options.html (look under `copy-command`).

**Comment by zuisong** [comment]
> 嘿@jinfagang- 我认为macos终端不支持OSC52，这是我们用来告诉它复制到剪贴板的方法。
> 
> 您可以使用一种解决方法，即使用外部命令进行复制。您需要为您的 mac 安装相关命令（我认为对于 macos 它是`pbcopy`），然后调整 Zellij 配置。
> 
> 更多信息在这里：[zellij.dev/documentation/options.html](https://zellij.dev/documentation/options.html)（在下面查看`copy-command`）。

It works for me, thanks. :smile:

**Comment by imsnif** [comment]
@jinfagang can we close this?

**Comment by jinfagang** [comment]
sure
