### ISSUE TITLE
Via SSH session, copying text to the local machine's clipboard is impossible

### ISSUE THREAD

**Issue by FSMaxB** [zellij-org/zellij#1677]
I recently had zellij running on macOS and connected to it via SSH. Trying to select and copy text, the terminal emulator's own selection capabilities didn't work, rather zellij copied the selected text into the clipboard of the remote host (the macOS system I was SSHed into).

Ideally this is how this should work in my opinion:
* Detect if running in an SSH session (There should be environment variables like `SSH_CONNECTION` or similar that allow detecting this)
* Allow the local terminal emulator to select and copy text locally

I am not sure if this problem can even be solved without completely loosing all mouse support though.

**Comment by imsnif** [comment]
Hey, by default Zellij uses the OSC52 signal to copy to the clipboard. This means it sends an instruction to your terminal emulator, and the terminal emulator is in-charge of placing it in the clipboard. Meaning that this problem then goes away and we always do the right thing.

Not all terminal emulators support this though, and because of it we have the `copy-command` (https://zellij.dev/documentation/options.html) config option as a workaround. These external utilities naturally can only copy something to the clipboard of the local machine though.

Could it be that your Zellij config has this copy command set?

**Comment by FSMaxB** [comment]
> Could it be that your Zellij config has this copy command set?

Yes, you're right, removing that, it just works. Sorry about that.

Thanks for your time in answering that and providing Zellij in the first place. Switching over from `tmux` I felt right at home!
