### ISSUE TITLE
copy text not working on ubuntu

### ISSUE THREAD

**Issue by jinfagang** [zellij-org/zellij#1699]
I just switch to ubuntu built-in terminal, now copy not work.

![image](https://user-images.githubusercontent.com/21303438/187363074-5d1567a9-38a1-4e55-83c7-01ecf494ee11.png)

it shows this but no text copied.
I forget how to fix it, this is **really** annoying..

**Comment by imsnif** [comment]
Hey @jinfagang - I just added a section to our FAQ about this, because I think like you - many users won't always remember what's happening here or how to fix this (I wish we had a way to make this "just work", but unfortunately we don't :( ).

What do you think? https://zellij.dev/documentation/faq.html#copy--paste-isnt-working-how-can-i-fix-this

**Comment by jinfagang** [comment]
I fixed by providing a config yaml, does the yaml can set to default if 80% users get this issue out-of-box? LIke set the copy command as defaults. (also I think it UI can indicates user if copy fails would better)

**Comment by imsnif** [comment]
So first - I'm not at all sure this affects 80% of users :)

But even if it did: we don't want to install an external utility for you. I don't know about you - but I would be very annoyed if a tool I downloaded just arbitrarily installed another tool for me!

About indicating this in the UI: we can't know that our default OSC 52 method didn't work. We send the signal to your terminal and it either uses it or it doesn't. We have no way of knowing. The only way we can know this is to read your clipboard and see if it worked... I think we can all agree that would be a bad thing to do :)

I'm happy it works for you now.
