### ISSUE TITLE
Attaching to the same sessions in two terminal windows with different sizes looks weird

### ISSUE THREAD

**Issue by Kushagra-0801** [zellij-org/zellij#1739]
**Basic information**

`zellij --version`: 0.31.4
`stty size`: 29 147
`uname -av or ver(Windows)`: Linux fa061866 5.14.0-1045-oem https://github.com/zellij-org/zellij/issues/51-Ubuntu SMP Mon Jul 4 06:41:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Further information**
1. Open a zellij session in one terminal window.
2. Attach to the same session in another window.
3. Change the size of one terminal window.
4. Observe as the other window (inner content) changes its size as well.

**Comment by jaeheonji** [comment]
Hi, @Kushagra-0801!

By default, in a Shared session, terminals connected to the session share the same terminal size.
So if one terminal changes its size, it can affect other terminals as well.

Therefore, it is difficult to determine exactly what the problem is now.
Could you please share the screen that comes out weird?

**Comment by Kushagra-0801** [comment]
I suppose weird was not the right word. I was indeed talking about the terminals changing size unexpectedly.

![Screenshot from 2022-09-19 13-11-39](https://user-images.githubusercontent.com/39802979/190971061-16499fd7-0cbc-4def-aeb4-d5d69b178bb6.png)

As you can see, in both the windows, the actual content resizes itself to the smallest size on each dimension

**Comment by jaeheonji** [comment]
Thanks for sharing the photo!

> As you can see, in both the windows, the actual content resizes itself to the smallest size on each dimension

Yes, As far as I know this is working correctly. The size of the terminal is output as the minimum value of each dimension. (Of course, it doesn't make sense to print the size as the maximum value.)

Because, shared session is a feature that shares the same screen.
If you only share content, and you want the each client to have a different UI, it will be another topic of adding new features.

**Comment by Kushagra-0801** [comment]
Alright. It would be awesome if content-sharing without size-sharing could be implemented but I am fine for now. I just wanted to make sure that this wasn't something on just my system. I think this issue can be closed now.
