### ISSUE TITLE
Mishighlighted text in nu shell

### ISSUE THREAD

**Issue by disilent** [zellij-org/zellij#1801]
When searching for text in nu shell, the text selection in the terminal is incorrectly processed if it is after a single or double quotation mark. This is not observed in zsh.

**Comment by jaeheonji** [comment]
HI @disilent!

I tried to reproduce the problem like this:
![example](https://user-images.githubusercontent.com/32578710/196128475-878a62b8-a810-4fdf-92dc-42d2c4986bcb.png)

Above is nushell and below is fish. Is this correct what you meant?

For reference, my environment is as follows:
* zellij 0.31.4
* nushell 0.69.1

**Comment by disilent** [comment]
Yes, it is.

**Comment by jaeheonji** [comment]
Cool, then I'll check it out :)

**Comment by jaeheonji** [comment]
I tried to some tests, and this seems to be a nushell-side issue. More precisely, it appears to be a problem with default theme of nushell.

![dev](https://user-images.githubusercontent.com/32578710/197683052-cbbab9bb-cce7-455e-9917-f38f1ac1dc51.png)

In the same environment, as above, if I remove the prompt on the right, the search will be highlighted normally.
So, this issue seems more related to [nushell/reedline](https://github.com/nushell/reedline).
