### ISSUE TITLE
Some emojis are not being aligned

### ISSUE THREAD

**Issue by delucca** [zellij-org/zellij#1816]
**Basic information**

`zellij --version`: 0.31.4
`stty size`: 56 192
`uname -av` or `ver`(Windows): Linux bighead 5.15.72-1-lts #1 SMP Wed, 05 Oct 2022 12:15:15 +0000 x86_64 GNU/Linux
`wezterm --version`: wezterm 20220905-102802-7d4b8249

**Further information**
While using Zellij, some emojis are not properly align. For example, look at the cloud emoji in my shell. Here it is outside of zellij:
![](https://i.imgur.com/FksWVPi.png)

And this is how it renders inside Zellij
![](https://i.imgur.com/yn58jaU.png)

**Comment by delucca** [comment]
hey @har7an thanks for your reply :)

Here is the output:
```%{^[[1;36m%}~%{^[[0m%} on %{^[[1;34m%}M-bM-^XM-^AM-oM-8M-^O  %{^[[0m%}%{^[[1;34m%}daniel%{^[[0m%}%{^[[1;34m%}@%{^[[0m%}%{^[[1;34m%}trilon.io%{^[[0m%} $
%{^[[1;32m%}M-bM-^]M-/%{^[[0m%} %

**Comment by har7an** [comment]
This is fascinating. I'm not sure how to fix it because this bit of zellij code is currently alien to me, but I know where to look now. I'll write down a few notes here:

The important bit from the output is this: `M-bM-^XM-^AM-oM-8M-^O`. This is a special notation type in `cat`, which it refers to as "M- and ^" notation. These actually code UTF-8 glyphs (in a format I don't quite understand, [here's more info on that][1]):

```
M-bM-^XM-^A = 0x2601
M-oM-8M-^O  = 0xfe0f
```

Now we have the Hex-codes for the icons. We can print them separately:

```bash
$ echo -e "\u2601"
☁
$ echo -e "\ufe0f"

$ echo -e "\u2601\ufe0f"
☁️
```

And that's exactly what you see: The second output is empty. This is a bug in zellij, because it seems we parse the Unicode codes wrong. Further [research about `\ufe0f`] shows that it is a *Variation Selector*, in particular it's [Variation Selector 16][2] (VS-16). There's a [good post on Stack Overflow][3] that explains what these do. In short, VS-16 is used to display emojis (like in the third output above: it has colors!).

Looking up what the other code is meant to represent we find that [`\u2601` is a cloud symbol][4], part of the Unicode standard since 1993. Above we see what VS-16 does: If we print only the cloud glyph, we see the (monochrome) broken symbol. What we need to do is, when we find `\ufe0f` in the output, apply this transformation to the preceeding character and print the Emoji-variant of this char instead.

Amazing, the things you can do with Unicode!


[1]: https://stackoverflow.com/questions/44694331/what-is-the-m-notation-and-where-is-it-documented
[2]: https://unicodeplus.com/U+FE0F
[3]: https://stackoverflow.com/a/63723069
[4]: https://unicodeplus.com/U+2601

**Comment by har7an** [comment]
I've had some discussion with my fellow colleagues and it turns out this is a known issue. It's being discussed in #1538.

**Comment by delucca** [comment]
Thanks @har7an I'll subscribe to that issue.

Should we close this one?
