### ISSUE TITLE
Wasm unwrap panic

### ISSUE THREAD

**Issue by ProjectInitiative** [zellij-org/zellij#1822]
**Basic information**

`zellij --version`: 0.32.0 (617b52f8f4b51282b25b061a207160979143a6c2)
`stty size`: 77 282
`uname -av` or `ver`(Windows): Linux generic 5.15.0-50-generic

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`alacritty --version`: alacritty 0.11.0-dev (4ddb6085)
`Gnome terminal`: Version 3.44.0 for GNOME 42

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

Was using an older build, upon update `zellij` command no longer works.

[zellij.log](https://github.com/zellij-org/zellij/files/9820968/zellij.log)

```bash
zellij --debug

Error occurred in server:

  × Thread 'wasm' panicked.
  ├─▶ Originating Thread(s)
  │   	1. ipc_server: NewClient
  │   	2. pty_thread: NewTab
  │   	3. screen_thread: NewTab
  │   	4. plugin_thread: Update
  │   
  ├─▶ At zellij-server/src/wasm_vm.rs:145:42
  ╰─▶ called `Result::unwrap()` on an `Err` value: RuntimeError { source: Trap(UnreachableCodeReached), wasm_trace: [FrameInfo { module_name: "<module>", func_index: 196, function_name: None,
      func_start: SourceLoc(118399), instr: SourceLoc(121927) }, FrameInfo { module_name: "<module>", func_index: 97, function_name: None, func_start: SourceLoc(59952), instr: SourceLoc(60199) },
      FrameInfo { module_name: "<module>", func_index: 102, function_name: None, func_start: SourceLoc(61748), instr: SourceLoc(61869) }, FrameInfo { module_name: "<module>", func_index: 509,
      function_name: None, func_start: SourceLoc(409244), instr: SourceLoc(427678) }], native_trace:    0: <unknown>
         1: <unknown>
         2: <unknown>
         3: <unknown>
         4: <unknown>
         5: <unknown>
         6: <unknown>
       }
         0: <unknown>
         1: <unknown>
         2: <unknown>
         3: <unknown>
         4: <unknown>
         5: <unknown>
         6: <unknown>
         7: <unknown>
         8: <unknown>
         9: <unknown>
        10: <unknown>
        11: <unknown>
        12: <unknown>
        13: <unknown>
        14: start_thread
                   at ./nptl/./nptl/pthread_create.c:442:8
        15: clone3
                   at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
      
  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)
        
        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
```

**Comment by tlinford** [comment]
Looks like your plugins have gotten out of sync, can you try clearing `.local/share/zellij`?

**Comment by ProjectInitiative** [comment]
I will give that a go. Side question though: in the future is the plan to get rid of the `unwrap` statements for more robust error handling?

**Comment by tlinford** [comment]
Indeed, check out #1753, @har7an has been doing great work on that front lately!

**Comment by ProjectInitiative** [comment]
Clearing that folder did not solve the issue. Rolling back to last release works fine, I might stick with that for now.

**Comment by iddar** [comment]
I have a similar error here 

```
Linux ariza-ml 6.0.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64 GNU/Linux
zellij 0.32.0
alacritty 0.11.0 (8dbaa0bb)
xfce-terminal 1.0.4
```


```sh
RUST_BACKTRACE=1 zellij --debug

Error occurred in server:

  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │   	1. ipc_server: NewClient
  │   	2. pty_thread: NewTab
  │   	3. screen_thread: NewTab
  │   
  ├─▶ At zellij-server/src/panes/plugin_pane.rs:166:18
  ╰─▶ Failed to receive reply from plugin. Please check the logs: RecvError
      
      Panic backtrace:
         0: <unknown>
         1: <unknown>
         2: <unknown>
         3: <unknown>
         4: <unknown>
         5: <unknown>
         6: <unknown>
         7: <unknown>
         8: <unknown>
         9: <unknown>
        10: <unknown>
        11: <unknown>
        12: <unknown>
        13: <unknown>
        14: <unknown>
        15: <unknown>
        16: <unknown>
        17: <unknown>
        18: <unknown>
        19: <unknown>
        20: <unknown>
      
  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)
        
        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
        
```

**Comment by imsnif** [comment]
This error happens because the plugins Zellij has loaded have not been compiled from the same commit (i.e. not using the same API contract) as Zellij itself.
It can happen because:
1. Zellij was compiled without recompiling the plugins, meaning it just took whatever was in the `assets` folder. This can happen for example if zellij was compiled with `cargo build` instead of `cargo make install /path/to/executable`
2. There are old assets in the cache folder, and so deleting the cache folder might help. You can find out what it is by issuing `zellij setup --check` and looking for `PLUGIN DIR`.

This should never happen in release builds (unless the same machine previously ran a non-release build with the same version number).

As a maintainer I'm sorry this complexity is on the user's shoulders. We're working on overhauling the plugin system in order to prevent this among other things. For now I can only heartily encourage users to only run release builds unless you plan to do Zellij development.

If none of these solutions work, you can try:
1. Running Zellij with `zellij --data-dir /tmp/non-existent-folder` to force it to re-use its internal plugin assets.
2. If 1 still doesn't work, there is a problem with the executable itself. You might want to get the executable from a different distributor (eg. download a precompiled version directly from our release).

**Comment by har7an** [comment]
@iddar I see you're running fresh from main, because there's a neat hint in your error output:

> ╰─▶ Failed to receive reply from plugin. Please check the logs: RecvError

If you check your logs at `/tmp/zellij-$(id -u)/zellij-log/zellij.log`, you'll see the cause (or in this case, a hint to the cause).

Did you see that message in the panic handlers output? Because if not I'd like to know how we can improve the messages visibility so other users recognize it better.

**Comment by har7an** [comment]
The new zellij release 0.32.0 will now perform version checks when loading the plugins. @ProjectInitiative would you mind trying out the new release and telling us what error you see then?

**Comment by ProjectInitiative** [comment]
Newest release fixed the problem. Thanks, closing.
