### ISSUE TITLE
[Codebase maintenance] refactor and rework the test framework

### ISSUE THREAD

**Issue by categorille** [zellij-org/zellij#183]
### Context on the test framework
(correct me if I am wrong on some technical stuff and I will edit this @imsnif)
The [integration tests](https://github.com/zellij-org/zellij/tree/main/src/tests/integration) work by, within each test function, starting Zellij with a [fake input-output struct](https://github.com/zellij-org/zellij/blob/695a75c36307c01e3ad08b3f2207df18995a34ab/src/tests/fakes.rs#L63) (here's an [example](https://github.com/zellij-org/zellij/blob/695a75c36307c01e3ad08b3f2207df18995a34ab/src/tests/integration/basic.rs#L47)). This `struct FakeInputOutput` implements the [`OsApi` trait](https://github.com/zellij-org/zellij/blob/695a75c36307c01e3ad08b3f2207df18995a34ab/src/common/os_input_output.rs#L142), which means Zellij treats it as any normal terminal IO struct. This struct allows us to feed Zellij a predefined sequence of inputs via the `FakeInputOutput`'s [`stdout_writer`](https://github.com/zellij-org/zellij/blob/695a75c36307c01e3ad08b3f2207df18995a34ab/src/tests/fakes.rs#L68) (continuation of the [example](https://github.com/zellij-org/zellij/blob/695a75c36307c01e3ad08b3f2207df18995a34ab/src/tests/integration/basic.rs#L48)), that will be handled in order by Zellij, each of them changing Zellij's state (number/size/position of panes/tabs, etc.). Additionally, the `FakeInputOutput` struct allows us to take **snapshots** of Zellij's state each times Zellij renders itself to the terminal. The tests functions can then assert that these state snapshots match the expected state of Zellij after certain inputs have been fed to it.

### The current state of things
The core logic is there, with the snapshot system and the fake IO structs. However, there are over 4600LoC of integration tests (`cd src/tests/integration/ && cat *.rs | wc -l`) as I am writing this, most of them being copy-pasted. The sequence of inputs that each test relies to reach the desired state is hard-coded ([other example](https://github.com/zellij-org/zellij/blob/695a75c36307c01e3ad08b3f2207df18995a34ab/src/tests/integration/resize_down.rs#L591)), and changing them, even with the right usage of `vim` macros, is tedious (but necessary for the tests to pass whenever we make changes to the keybinds, see [this PR](https://github.com/zellij-org/zellij/pull/181#issuecomment-777889254)).

### How shings should be
- There shouldn't be repetition in the tests functions. There's probably some abstracting away to do (all the test functions within each integration test file work pretty much exactly the same, just with a different input sequence)
- The framework's logic should move in the direction of independence from Zellij's actual codebase, i.e. there should be as little LoC as possible in the actual codebase that have "making the tests work" as their sole purpose
- The tests shouldn't rely on hard-coded input sequences (this probably requires that the input module be reworked first, see issues)

### Some encouragement
I can understand how tackling a test module that is over 5KLoC long can be a bit scary, but remember that most of them are duplicated and that the goal is to reduce the amount of LoC by a LOT. Once you get the hang of the test framework's logic, things shouldn't look that bad anymore.

**Comment by imsnif** [comment]
You got everything right, except:
1. The snapshots are taken each time Zellij renders itself to the terminal (calls `flush` on stdout here: https://github.com/zellij-org/zellij/blob/main/src/tests/fakes.rs#L51). This might happen more or less than once per fake key input.
2. A minor nitpick: the specific hack you mentioned in the code base is because Zellij in this case is "wrong" and just happens to work outside the context of the tests. The tests expose a bad behaviour (relying on the process ending in order to close the threads).

**Comment by imsnif** [comment]
Btw, there's also another bit of complication that is worth mentioning.
The snapshots created by the testing frameworks are not Human readable. They are snapshots of VT/ANSI code (called "frames"). Each test case makes them Human readable by using Zellij itself to interpret them (yes, we are using Zellij to test itself :) ). This happens here: https://github.com/zellij-org/zellij/blob/main/src/tests/utils.rs#L10

The process (in general) works like this in each test case:
1. Run `start` with the fake OS interface as you mentioned.
2. End up with a series of frames in ANSI/VT form.
3. Instantiate a new `TerminalPane` (the same one used by Zellij)
4. Feed those frames to the pane instance so that it creates a Human readable snapshot for every one of them.
5. Assert those Human readable snapshots against a predetermined state.

While we don't *have* to do this and can technically just assert the ANSI/VT frames, if something fails in that case it would be very hard to have the test framework explain itself to the developer.

**Comment by imsnif** [comment]
So, this is all either done or done in a different way. The old integration testing framework is gone. In its place we have:

1. An end-to-end testing framework that tests Zellij as a blackbox inside a docker container and verifies the output (and is generally considerably less developer hostile and more stable than the previous framework)
2. Unit tests in all relevant modules (at least the ones that were covered by the old testing framework)
