### ISSUE TITLE
Initial keystrokes are lost when typed in too fast

### ISSUE THREAD

**Issue by FSMaxB** [zellij-org/zellij#1989]
`zellij --version`: `zellij 0.33.0`
`stty size`: `26 82`
`uname -av` or `ver`(Windows): `Linux hostname 6.0.10-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 26 Nov 2022 16:51:18 +0000 x86_64 GNU/Linux`
`tmux`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`bash --version`: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
`alacritty --version`: `alacritty 0.11.0 (8dbaa0bb)`

**Further information**
When starting up `zellij`, if I type a command too quickly, the input gets lost. e.g. I'm starting `zellij` and immediately type `ls<enter>`, nothing happens.

If I wait for a bit and only then start typing, it works.

This is in contrast to `tmux` where this works in either case.

Probably `zellij` needs to start listening to `stdin` immediately at startup and not only once everything is initialized, but I'm not entirely sure.

**Comment by raphCode** [comment]
I can at least explain what is going on: At startup we query the terminal for some colors due to our sixel support, and the terminal responds by "typing" back its response. This takes some time, and the current implementation blocks the visual input until that is done. Otherwise the control codes might end up being typed in the shell, which sometimes happens if things go wrong.
So the delay is deliberate, but I agree it is annoying, especially one is not interested in using the sixel stuff.

**Comment by raphCode** [comment]
We introduced a loading screen while the input is blocked so at least users are aware of the delay at startup.

https://github.com/zellij-org/zellij/releases/tag/v0.34.3

**Comment by FSMaxB** [comment]
Thanks!
