### ISSUE TITLE
Slow opening : Querying terminal emulator

### ISSUE THREAD

**Issue by fulljackz** [zellij-org/zellij#2001]
**Basic information**

`zellij --version`: 0.34
`stty size`: 14 76
`uname -av` or `ver`(Windows): Linux LIN-ELN 5.19.0-26-generic #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`tilix --version
Versions
        Tilix version: 1.9.5
        VTE version: 0.70
        GTK Version: 3.24.34`

**Further information**
Since v0.34, there is a slow down during the open process. A message is briefly prompted during the load : `Loading Zellij Querying terminal emulator for default colors and pixel / cell ratio...`.

You'll find logs and video in attachment.

Regards,
[Screencast from 2022-12-09 09-48-52.webm](https://user-images.githubusercontent.com/12140932/206663337-9de386e9-1f8e-4b65-be5b-6c660b24e16e.webm)
[zellij-27.log](https://github.com/zellij-org/zellij/files/10193263/zellij-27.log)
[zellij.log](https://github.com/zellij-org/zellij/files/10193264/zellij.log)

**Comment by imsnif** [comment]
This is not a bug, it's a feature :)

We have to query the terminal emulator for default colors, pixel/cell ratio, etc. before starting. The terminal emulator replies on STDIN - and so while it replies as a user you can't type anything (because it will get mixed up with the reply).

Up until now we did this "under the hood" and so you didn't see anything but would lose input if you typed quickly. Now we have a loading screen. It's 0.5 seconds, in any case...

**Comment by davxy** [comment]
> We have to query the terminal emulator for default colors, pixel/cell ratio, etc. before starting.

These values cannot be cached somehow?
