### ISSUE TITLE
Removing Nix support from the repository?

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#2008]
This repository has Nix support as part of the code-base. This decision was made back when one of the active maintainers was an avid Nix user and used it for his environment. Alas, this is no longer the case and we are left with:

1. A Nix build-pipeline we need to maintain (right now it's broken after some repository changes)
2. 5 bare files and 1 folder in the core of our project that clutter things up
3. A badge on the README that is increasingly misleading

I'm very sympathetic to Nix users and would like them all to feel welcome, but in my mind it would be better to serve their needs outside of this repository just like the other packagers (eg. debian, arch, homebrew, etc.)

This is not set in stone though and I'm happy to hear dissenting opinions. Tagging @a-kenji especially.

**Comment by imsnif** [comment]
ping @a-kenji - I'm going to give this a week, if I hear no dissenting opinions I will go ahead and remove nix support from this repository.

**Comment by imsnif** [comment]
After hearing no dissenting opinions past the deadline, I have removed nix support from the repository.

As mentioned in the PR: if there's someone from the nix community who wishes to package and distribute Zellij in a nix-friendly way in some way that will not involve placing assets in the repository, I'd be happy to provide whatever help I can.

**Comment by a-kenji** [comment]
Thank you for the ping!
Since 7 days are not over yet:

I agree that it makes sense to remove the build infrastructure at this point.

It did provide a lot of nice features: For instance any person with linux, or macos could always try out the main branch without problems (the plugins were always correct), and without the need of rebuilding and using precious battery power.

Tough through time constraints, and me probably being the only active maintainer on it. It makes sense to sunset it.

> A Nix build-pipeline we need to maintain (right now it's broken after some repository changes)

I fixed it very soon after it happened, since I took ownership of the code I tried to keep it very up to date. I am not too sure, if it was broken as of the time writing this issue.

> 5 bare files and 1 folder in the core of our project that clutter things up

From my perspective it did not clutter things up, but make things more easily discoverable. But that is not a prerequisite. This all could be in 1-2 files, if that is preferable.

> A badge on the README that is increasingly misleading

I agree, once the build does not happen, it is misleading!

I would prefer if the nix shell would stay, as it still would make it more accessible for more people to contribute to the project. That could be handled in 1-2 files and would not contribute to any CI failures. But I do understand if we ultimately decide to not go that route.

**Comment by imsnif** [comment]
Thanks for your thoughts @a-kenji - as mentioned in the linked PR, I already removed nix repository this morning as the deadline passed. This repository no longer has built-in nix support.

**Comment by TheLostLambda** [comment]
I'm sure @a-kenji knows a *lot* more about Nix than me, but I've just been bitten by the Nix bug as well and if I understand correctly Flakes might be a one-file solution for building Zellij and running it (without needing any Rust tooling installed) and could standardize the development environment of contributors too. Just dropping this here because I'd not noticed Nix support was gone until now!

https://xeiaso.net/blog/nix-flakes-1-2022-02-21

**Comment by imsnif** [comment]
Thanks for your thoughts @TheLostLambda - but we already have a build system. We also already have a packaging solution. I have a lot of empathy for people liking a certain piece of technology, but this particular one is solving a problem we do not have.

In addition, it creates a lot of noise in the repository (files in the project root, constant PRs to update them, CI failures, etc.)

I brought this issue up consistently over months and received mostly silence. Even after giving this public ultimatum I received no timely responses. This tells me that those actively maintaining Zellij do not feel strongly about keeping nix support.

The decision has already been made. I tried to lock this conversation to prevent going into this further, as I feel past this point it mostly boils down to "I like nix / I do not like nix". Apparently though, Github's locking mechanism does not include collaborators. So I'm asking: please let's drop this and move on.
