### ISSUE TITLE
Zellij pane freezes when trying to enter search mode on a locked pane

### ISSUE THREAD

**Issue by mb2g17** [zellij-org/zellij#2017]
**Basic information**

stty size: `27 120`
Version of zellij: `0.34.3`
uname -av: `Linux [my hostname] 4.15.0-197-generic #208-Ubuntu SMP Tue Nov 1 17:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Further information**
Lock the current pane with ctrl + g
Try going into search mode within the locked page with ctrl + s
Unlock pane with ctrl + g again
Find that you cannot type into the pane

[zellij.log](https://github.com/zellij-org/zellij/files/10209780/zellij.log)

**Comment by mb2g17** [comment]
Hi, this still happens with the default config 😓  for further context, I'm using Windows Terminal, and ssh-ing into a remote linux session, where zellij is installed and ran.

**Comment by raphCode** [comment]
Is this only happening inside zellij / one zellij pane? I know that `Ctrl-S` is sometimes used by the terminal emulator to pause terminal output altogether:
https://en.wikipedia.org/wiki/Software_flow_control

**Comment by mb2g17** [comment]
Hi, I've just tried your steps @raphCode and it does seem that ssh is pausing output on `Ctrl-S`. However using `Ctrl-Q` to unfreeze while in zellij closes the session. I suppose a quick workaround would be to rebind the keyboard shortcut to close the session to something else in the config. Thanks for the info!

**Comment by raphCode** [comment]
A "proper" solution would probably involve finding out where the software flow control happens, and disable it.
[This answer](https://superuser.com/a/1096913) says ssh just forwards everything including `Ctrl-S`, so it must be on the remote host.
I think the kernel does this for the pty of the shell, since zellij itself is always responsible (can toogle Lock mode even when shell appears frozen).
The pty between ssh / zellij can't be it otherwise zellij would freeze too.

---

After reading the `stty` manpage, I proudly present the solution:

`stty -ixon`

Execute this in the relevant panes or add it to your .bashrc :D

**Comment by raphCode** [comment]
The reason why @imsnif can't reproduce is that he uses the fish shell, and as friendly as it is, it disables flow control on startup :)
