### ISSUE TITLE
exa tree command crush

### ISSUE THREAD

**Issue by digika-ding** [zellij-org/zellij#2023]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Run `stty size`, copy the result and attach it in the bug report
4. Recreate your issue.
5. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: zellij 0.34.3
`stty size`: 94 203
`uname -av` or `ver`(Windows): Darwin WeibingacStudio 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`exa --version`: v0.10.1 [+git]
`kitty --version`: kitty 0.26.5 created by Kovid Goyal

**Further information**
Reproduction steps, noticeable behavior, related issues, etc
`exa --long --header --icons --sort=modified --group-directories-first --time-style=long-iso --group --created --modified --tree` create a large output

In my case zellij-log were not created.
The output was **Error occurred in server: Buffer full**

**Comment by imsnif** [comment]
This happens when the terminal emulator (Kitty, in this case) takes too long to read from STDOUT and Zellij's buffer gets filled. Note that the session itself isn't lost and you can manually attach back to it. I want to add a feature that does this automatically, but there's not a lot more we can do about it.

If this happens often, I'd recommend trying another terminal emulator - Alacritty is very fast.
