### ISSUE TITLE
List opened tabs in a session?

### ISSUE THREAD

**Issue by thisismygitrepo** [zellij-org/zellij#2098]
Unless I'm very much mistaken, there doesn't seem to be any way to list the opened tabs, just like you can list opened sessions. Can we please have this feature? Absence of that, the `action` subcomamnd doesn't give that much power.

Thanks.

**Comment by naosense** [comment]
@imsnif I only found a way to get the tab list by `get_tabs_mut`, which belongs to the `Screen` struct, but I don't know how to get the current screen

**Comment by imsnif** [comment]
Hey @naosense - implementing this might be interesting, since we will need to create a bit of a client/server communication interaction going.

I think what you'll want to do is send a new `Action` to the server, maybe something like "QueryTabNames"? Then, the server will need to send a new kind of `ServerToClient` message, something like `Log`, which would be similar to `ServerToClient::Render` - the only difference is that if this is a "normal" client, it will log this info to `zellij.log` and if it is a `cli_client` it will log it to screen - so the client gets a response.

I realize this is probably a longer answer than you asked for, but this is not a super trivial feature with the infrastructure we have now. I'd be happy if you want to work on it and dig deeper though.
