### ISSUE TITLE
Glitches when running asciiquarium inside zellij

### ISSUE THREAD

**Issue by gorbak25** [zellij-org/zellij#2256]
Hi!
Came across this project, started the demo `bash (curl -L zellij.dev/launch | psub)` inside `gnome-terminal`, after playing a bit i tried to launch `asciiquarium -c`.
Unfortunately the animation glitches 
![image](https://user-images.githubusercontent.com/1352848/223890082-5bd9fe9f-20d5-47f8-b5ef-6bb01944e239.png)
![image](https://user-images.githubusercontent.com/1352848/223890124-8ab69f45-ef56-44cf-a7e2-ac30c010dcf9.png)
I've tried to reproduce those artifacts(black areas) while running `asciiquarium` normally, even with weird terminal resolutions i don't get any glitches.
I have no issues with `asciiquarium` under `screen`  or `tmux`.

**Comment by imsnif** [comment]
Hey @gorbak25 - thanks for reporting this issue!

I issued a fix for the most obvious parts, but I think there might be others - and I found myself staring at ASCII fish too long to reproduce them :)

If you'd like them fixed as well, please include the logs in our ISSUE_TEMPLATE (you'll be prompted when opening an issue) in order to help me fix these. Attaching them will allow me to reproduce this immediately.

Thanks!

**Comment by gorbak25** [comment]
@imsnif thanks for the fix :) 

I've tested out today's main branch and the issue looks to be fixed. Just to be sure I left asciquarium run in the background for a few minutes and there still seems to sometimes be an issue(when the big ship which sometimes appears leaves the screen). I will try to provide a better bug report.
