### ISSUE TITLE
Unable to run fish functions/aliases from layouts

### ISSUE THREAD

**Issue by AlgorithmEnigma** [zellij-org/zellij#2265]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**Basic information**

`zellij --version`: 0.35.1
`stty size`:
`uname -av` or `ver`(Windows): 6.2.2-arch1-1

List of programs you interact with:
`fish version:` 3.6.0

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

I try to run a custom fish function using a layout and it says command not found.
Fish is set as the default shell for zellij, does it not run commands as the fish shell but as some other shell?

**Comment by kseistrup** [comment]
The way I see it:

Fish functions are run by fish when fish runs in zellij. Zellij is most likely using a system call to spawn the fish binary. Such a system call cannot be used to spawn a fish function.

Depending on the function you need to call, you may be able to run it by using `fish -c 'my_function'` instead of just `my_function`.

**Comment by imsnif** [comment]
Hey @kseistrup has it right. You can do something like:
```kdl
pane command="fish" {
    args "-c" "your_fish_function_here"
}
```
