### ISSUE TITLE
equivalent to `tmux switch-client -l`

### ISSUE THREAD

**Issue by WaylonWalker** [zellij-org/zellij#2269]
tmux provides a flag to switch to the last session that I was attached to.  Not the next or previous index, but the last one I was attached to.  I use this often to jump between two projects quickly.  Is there an equivalent in zellij.

## tmux switch-clent man page.

``` man
     switch-client [-ElnprZ] [-c target-client] [-t target-session] [-T
             key-table]
                   (alias: switchc)
             Switch the current session for client target-client to
             target-session.  As a special case, -t may refer to a pane
             (a target that contains ‘:’, ‘.’ or ‘%’), to change session,
             window and pane.  In that case, -Z keeps the window zoomed
             if it was zoomed.  If -l, -n or -p is used, the client is
             moved to the last, next or previous session respectively.
             -r toggles the client read-only and ignore-size flags (see
             the attach-session command).
                                                                           
             If -E is used, update-environment option will not be ap‐
             plied.
                                                                           
             -T sets the client's key table; the next key from the client
             will be interpreted from key-table.  This may be used to
             configure multiple prefix keys, or to bind commands to se‐
             quences of keys.  For example, to make typing ‘abc’ run the
             list-keys command:
                                                                           
                   bind-key -Ttable2 c list-keys
                   bind-key -Ttable1 b switch-client -Ttable2
                   bind-key -Troot   a switch-client -Ttable1

```

**Comment by elijahmanor** [comment]
Hmm, not aware of that (yet). I wrote my own [session switcher](https://gist.github.com/elijahmanor/a8af9a19e7b12b4bde7fa9b9d4b7037d) that works inside or outside of a zellij instance. However it is macOS specific atm. Zellij is going to be working on a switcher plugin soon-ish, but it's not ready yet.

**Comment by WaylonWalker** [comment]
Thanks for the inspiration @elijahmanor, I think I can get something working similar to my tmux workflow from this.   I might need to wait till at lease switching sessions from inside of a zellij session to fully adopt.  I've replicated your macos hack with a kitty terminal hack, so it at lease works with local sessions where I only have one kitty instance open.

**Comment by elijahmanor** [comment]
@WaylonWalker ohh, I like the sounds of "a kitty terminal hack". I'll need to look into that.

**Comment by elijahmanor** [comment]
Ohhhhhhhhh loving this! Thank you @WaylonWalker

**Comment by jcaffey** [comment]
> Hmm, not aware of that (yet). I wrote my own [session switcher](https://gist.github.com/elijahmanor/a8af9a19e7b12b4bde7fa9b9d4b7037d) that works inside or outside of a zellij instance. However it is macOS specific atm. Zellij is going to be working on a switcher plugin soon-ish, but it's not ready yet.

Thank you! I now have enough to switch from tmux. Looking forward to the plugin for switching. Thanks for the great work!

**Comment by stefanpartheym** [comment]
I also made my own version of a session manager/switcher in my dotfiles repo: https://github.com/stefanpartheym/dot/blob/main/packages/scripts/zs

It supports switching to the last/recently used session by using two files. Here is some general information, maybe it can help some of you:

# zs - Alternative zellij session manager

This script is supposed to replace the builtin zellij session manager.

## Differences between `zs` and the builtin zellij session manager

The main feature `zs` provides - which zellij currently lacks - is that you can switch to the last used session. A feature, also known from tmux.
It also uses `fzf` to fuzzy find active sessions, dead sessions, zoxide locations and paths in the home directory. I like `fzf` way more than the builtin zellij session manager, as it provides vim keybindings (like `ctrl+n` and `ctrl+p` for next and previous entry).
Currently, `zs` lacks the feature to create a new session, as it is currently possible with the builtin session manager.

## Configuration

In order to use `zs` you need to configure zellij to use it. See the following examples on how to do that.

Replace the builtin session manager:

```kdl
# ...
keybinds {
    # ...
    shared_except "locked" {
        # ...
        // Session manager
        bind "Alt s" {
            Run "zs" {
                floating true
                move_to_focused_tab true
                close_on_exit true
            }
            SwitchToMode "Normal"
        }
        # ...
    }
    # ...
}
# ...

```

Use the "Switch to last session" feature:

```kdl
# ...
keybinds {
    # ...
    shared_except "locked" {
        # ...
        // Switch to recent/last session
        bind "Alt r" {
            Run "zs" "last-session" {
                floating true
                move_to_focused_tab true
                close_on_exit true
            }
            SwitchToMode "Normal"
        }
        # ...
    }
    # ...
}
# ...

```
