### ISSUE TITLE
Think about using the 2018 path version.

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#231]
The 2018 version prefers not to have a mod.rs in a module folder.

Example:
2015
.
├── lib.rs
└── foo/
    ├── mod.rs
    └── bar.rs
vs
2018
.
├── lib.rs
├── foo.rs
└── foo/
    └── bar.rs

https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html#no-more-modrs

I personally think this format makes slightly less sense when running `tree` in a folder,
but does make more sense when working in the actual file, in an editor, or for searching
the specified file.

Does it make sense to switch to that format for zellij?

**Comment by imsnif** [comment]
I don't have a strong opinion either way. @denismaxim0v has done a lot of work on file structure in the repo though... what do you think @denismaxim0v ?

**Comment by denismaxim0v** [comment]
Hmm, don't have a strong opinion here either. But I'm used to thinking of lib.rs as an equivalent of main.rs with a difference you can't run it directly. So that would mean we'd have only one lib.rs. With that being said, I think it makes a bit more sense, to me personally, to use `mod`ules instead of extending the main project. Plus I see most of the big projects being organized with mods, so I might be biased just because I'm used to it

**Comment by a-kenji** [comment]
No problem! I just came about it, while skimming the edition guide and thought it would be good to talk about it.
