### ISSUE TITLE
Alt + [] (toggle between horizontal and vertical split) doesn't work with custom layout

### ISSUE THREAD

**Issue by gmr458** [zellij-org/zellij#2593]
When i don't set `default_layout` the keybinding Alt + [] works but when I use my custom layout it doesn't work.

**Comment by imsnif** [comment]
Hey, this happens because the horizontal/vertical split layouts are [swap layouts](https://zellij.dev/documentation/swap-layouts.html). We provide some default ones for the default layouts (eg. horizontal and vertical) but for your custom layout we cannot guess how it would look like or what it should do.

You can define them or your own, or even use the default ones and adjust them as you like. More information provided in the link.
