### ISSUE TITLE
Question about pushing wasm files

### ISSUE THREAD

**Issue by IssacSchneizer** [zellij-org/zellij#2616]
From what I understood, wasm files are those nifty executable files that come about after compilation. Traditionally, it was common advice not to include them in repositories to keep things nice and small.

But  I noticed that there are wasm files in this repository, and I'm genuinely curious to know why. Is there something I'm missing? I'm just a bit concerned about the repo size, which is currently sitting at a hefty 100MB. That seems quite substantial.

**Comment by imsnif** [comment]
Hey, while I agree this is not ideal, we need to include these files as part of our executable (these are the built-in plugins). We can't do this as part of our CI because when publishing to crates.io we have some issues with cross-crate linking (eg. some crates can't compile without these assets and they are not the ones creating them in their isolated publishing environment). For the same reasons we can't rely on build.rs files. In short, everything is terrible.

**Comment by Zykino** [comment]
Is it possible to use git-lfs to both commit this files but not commit big binary files?
Or maybe it won’t help here?

**Comment by Zykino** [comment]
But they are seen as binary files by git right? git-lfs store them in the "lfs server" (like a dropbox) and only store a reference file to it.

So when the binary file change, if they are stored in git they are dupliced in the history each time. In lfs they are all stored in the "folder", and the git repo history only have a light "text file" that reference to it.
=> A pull with lfs only get the version of binary you need for the checkouted branch hash, otherwise you get all of the historical references.

But yeah 100Mo is not that much (In 3years of project, storing libs.a files my work repo is over 6Go…)

**Comment by imsnif** [comment]
Thanks for the suggestion, but as developer time is a much dearer process in our context than repository size (especially in such a negligible size) I think we're good for now.
