### ISSUE TITLE
Screen tearing and flickering with editors (helix/nvim)

### ISSUE THREAD

**Issue by cjauton** [zellij-org/zellij#2677]
I am having an issue in editors such as helix and neovim where quickly move half pages down results in screen tearing and slight flashing. I am using Wezterm + Zellij + helix/nvim. It happens in all configurations, fullscreen, with and without other panes, and doesn't change if resized. Not sure if this is the correct way to open this issue.

**Comment by imsnif** [comment]
Hey, thanks for reporting - but in this way it's a bit inactionable for us as maintainers. Personally I don't 100% understand what you mean. There are instructions in the issue template about how to report a graphical issue, but in this case I think a good start would be some sort of video that captures the issue.

**Comment by imsnif** [comment]
Alright, thanks for the videos!

Zellij is not a 60fps application, and there can be some very minimal redraw delays as demonstrated here. We do performance optimizations here and there (eg. large amounts of scrolling text appear very smoothly in Zellij because we optimized that part heavily), but this has not yet been done to all parts of the application.

This sort of work is something we'll do closer to a `1.0`.
