### ISSUE TITLE
Documentation and feature request

### ISSUE THREAD

**Issue by bitcoinmeetups** [zellij-org/zellij#2728]
Hi,

I'm Mr. Cygot, a very friendly guy.

Documentation request:

Please put the installation instructions on the README.md page front and center so everyone can see them. You want people to actually install right? The instructions belong in the README.md file.

Also please make installation instructions for Debian running on Raspberry Pi 4. It's a popular platform, don't skip it.

I came here because I saw you added sixel support. So, 40 years after the Commodore 64, Linux Terminals are finally getting graphics : )?

**Comment by imsnif** [comment]
Nice to meet you Mr. Cygot!

I totally agree with you about the installation instructions being in the README.md file! We definitely want people to install the software and that's why we put them there: https://github.com/zellij-org/zellij#how-do-i-install-it

This section includes all installation methods we as maintainers are answerable for. The rest are third party installations that are managed by the community and we link to out of convenience (that's why they're in a separate page).
