### ISSUE TITLE
Add Nix Flake

### ISSUE THREAD

**Issue by yoav-lavi** [zellij-org/zellij#2784]
Would be useful (IMO) to add a Nix flake (see for example https://github.com/helix-editor/helix/blob/master/flake.nix [the nixpkgs configuration for Zellij is [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/zellij/default.nix) and home-manager is [here](https://github.com/nix-community/home-manager/blob/master/modules/programs/zellij.nix)]) so Nix users (using flakes) can easily point to a "nightly" version of Zellij. 

This would allow users to configure an input and overlay to use the GitHub `main` version of Zellij.

This would also allow Nix users to contribute more easily.

(with `helix`:)

```nix
   # inputs ...
    helix = {
      url = "github:helix-editor/helix";
    };
    # ...
```
```nix
   # ...
    overlays = [
      (self: super: {
        inherit (helix.packages.aarch64-darwin) helix helix-unwrapped;
      })
    ];
    # ...
```

**Comment by clo4** [comment]
I wish. But it looks like this won't happen: #2008

Best choice is probably to do something similar to do something similar to [mitchellh/zig-overlay](https://github.com/mitchellh/zig-overlay). I'd say, have a flake in a separate repository, then you can add two inputs to your own flake: one for the zellij flake, and one that tracks this repo. You could then override the zellij flake's input using your own.

That would end up looking something like this:

```nix
{
  inputs = {
    nixkpgs.url = "github:nixos/nixpkgs/nixos-unstable";
    zellij-latest = {
      url = "github:zellij-org/zellij";
      flake = false;
    };
    zellij = {
      url = "github:clo4/zellij-flake";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.zellij.follows = "zellij-latest";
    }
  };
}
```

Of course, this would all be made much simpler by just having a flake in this repo.

NeoVim has a `contrib` directory that contains its flake. This makes it pretty clear from the outset that it's not officially supported. However, since one of the stated reasons for not supporting Nix is to not have the maintenance burden of reviewing PRs to fix broken builds, it would make more sense to instead have the flake in another repository entirely IMO

**Comment by imsnif** [comment]
I very much appreciate everyone's thoughts on this and love for nix, but from my perspective as a non-nix person (total respect for nix of course, it's just not my jam) - I don't want to have to learn a new domain language (flakes, overlays, home-manager, etc.) to manage and maintain this repository.

The way I see it, we already have a build system for internal use (xtask) which, while not perfect, totally fits our needs. I don't want added complexity here.

While I don't know Nix very well, I'm sure there are other ways to use it that do not involve adding assets to this repo.

As a side note: I very much do not recommend running a non-release build (eg. running directly from main) unless you're developing Zellij.

Thanks for understanding!

**Comment by alxpettit** [comment]
@imsnif 

While I respect and understand your decision on this matter, I should mention that you probably _wouldn't_ need to really _maintain_ the flake part, if you were to have it in the repo. With toolsets like naersk, the Nix interpreter will automatically read the Cargo.toml & Cargo.lock files, and use those -- so it's literally just a matter of maintaining the Cargo build-system itself (unless you have C dependencies). :P

Anyway, just thought I would be remiss if I didn't mention that.

I can verify what @clo4 said -- Zellij builds beautifully as a flake. I went ahead and packaged it separately as a [flake](https://github.com/alxpettit/zellij-flake). It automatically pulls in this repo as a dependency, sets up the Rust toolchain, builds and runs. The only problem is that the flake.lock needs to be updated in lockstep, ideally with CI testing to make sure nothing breaks. I'm not sure how to manage that without taking too much of my time, but if anyone has any ideas feel free to suggest them.

For anyone reading this who is using Nix flakes and is new to them, you can run the one I made by doing: `nix run "github:alxpettit/zellij-flake"` Hopefully I can find the time to maintain it. PRs welcome, of course.

**Comment by imsnif** [comment]
Hi @alxpettit - thanks for pointing this out. However, this is still maintenance. Even if everything goes perfectly, I have to know what `naersk` is, I guess I have to merge upgrades here and there... maybe it's not working for someone (for whatever reason) and I have to look into it... and then of course it leaves dotfiles in the repository that clutter it up and make things confusing.

And all of this without providing the repository with any benefits that we do not get from our existing CI/build-system/packaging solutions. As I mentioned - I am very sympathetic to nix users (you are often very smart and nice people!) but IMO a git repository is not the place for one's personal environment. I'm happy you put up an external solution that can serve that purpose for those interested.

**Comment by alxpettit** [comment]
Fair enough :)

Feel free to point people to my [nix flake repo for zellij](https://github.com/alxpettit/zellij-flake) or link to it if you want. Up to you!

I'll _do my best_ to maintain it, though no promises. I added workflows courtesy of DeterminateSystems to automatically make PR for flake lock updates, so that it can stay roughly synchronized with your repo! :D Although that approach is new to me, I figured it would be a good idea to experiment with automating this.

Anyway, thanks for being patient and understanding. Github really needs more of that, in general. Have a good day!
