### ISSUE TITLE
Hard to read colors when using Gruvbox Light theme.

### ISSUE THREAD

**Issue by papey** [zellij-org/zellij#2790]
Hi :wave: 

I'm having some issues with the Gruvbox Light color theme in Zellij (`zellij 0.38.1`)

My config is pretty simple : 

```
theme "gruvbox-light"
```

And I get

![2023-09-16-180123_1080x196_scrot](https://github.com/zellij-org/zellij/assets/17273325/96d38a97-94c6-4abd-9e9a-a5368278dfda)

It's almost impossible to read. I have tried multiple terminal (without a big hope to be honest) and it was the same behavior on all of them. I can rework a bit if you want just let me know.

Thanks a lot.

**Comment by papey** [comment]
Ok, so, the color causing the issue is the fg one, I have changed it to `fg "#665C54" (fg3, from Gruvbox). I can be changed to fg4 for even better clarity. I'll make a PR for that soon.

**Comment by papey** [comment]
👍

**Comment by apraga** [comment]
I would like to re-open this issue if possible. Using alacritty's gruvbox-light theme and zellij `gruvbox-light` : 
1. Pressing `Ctrl` gives text very hard to read on the different menu : 
![zellij-gruvbox-light](https://github.com/zellij-org/zellij/assets/914687/c714bc79-1504-4f2d-b316-e3b13b289cb8)

2. The top banner is on a black background but I would expect a light background (like catppuccin-latte). Is that by design ?
![zellij-gruvbox-light-2](https://github.com/zellij-org/zellij/assets/914687/c075ac85-93f3-4e44-b54a-34f579d218b5)

Gruvbox-dark does not have, on the contrary, these issues. I am using zellij 0.39.2. Any idea about this ?
Thanks,

**Comment by papey** [comment]
I did not modify any of this in my PR IRRC. I think most of the light comes from dark theme modified, so there are still progress to make to make it more tailored to white version. If you want you can open a PR, look at [mine](https://github.com/zellij-org/zellij/pull/2791) for inspiration about how to tweak colors. Cheers !
