### ISSUE TITLE
Vulnerable cranelift-codegen 0.86.1 is being used

### ISSUE THREAD

**Issue by glebpom** [zellij-org/zellij#2947]
cranelift-codegen v0.86.1 has the critical security issue [CVE-2023-26489](https://avd.aquasec.com/nvd/2023/cve-2023-26489/) . Please upgrade wasmer to a newer version.

**Comment by imsnif** [comment]
I think @tlinford mitigated this with a workaround and can say more.

**Comment by tlinford** [comment]
The changes in https://github.com/zellij-org/zellij/commit/9f130a3ef903ca7f3e7745291e8e0464110c7acd should adress this.

Upgrading to the latest wasmer is a non trivial task unfortunately, and even going to the first version where this is resolved is a lot of work because one needs to switch from wasmer-wasi to wasmer-wasix.

**Comment by imsnif** [comment]
Thanks @tlinford 

It's also not just about the amount of work but also that we don't want to use wasix because we don't feel it's stable enough even when we disable the optional features at compile time.

In any case, thanks for your vigilance @glebpom !

**Comment by glebpom** [comment]
it's not completely a vigilance, more like security scanners don't treat zellij as secure (`cargo-auditable` + `trivy`), which is still a problem, even with the workaround. @imsnif

**Comment by imsnif** [comment]
I'm sorry - the security vulnerability has been addressed (as per the CVE itself), there's not a lot I can do about the scanners...
