### ISSUE TITLE
scrolling when text updates

### ISSUE THREAD

**Issue by tekakutli** [zellij-org/zellij#306]
running mpv in audio-only mode led me to discover that if I scroll, the text update happens in the last >visual< line, not the actual last line as one expects it to happen

I imagine this would happen with any application that updates the terminal while one scrolls

so I tested it with a bash for loop printing and I discovered a different? bug, it doesn't allow me to scroll while it prints

**Comment by imsnif** [comment]
Thanks for the report! I think there are two issues here (though I have not yet investigated them, just guessing for now):
1. The bash loop: Right now scrolling works like this: if new characters are printed to the terminal, the scrolling is reset. This is not the best UX but is kind of a workaround to a design issue.
2. Updating while scrolling: I think this is a simpler bug. I would guess this can be solved by replicating the behaviour described in the previous point for any input received from the terminal (eg. cursor movement, styling change, etc.)

**Comment by tlani** [comment]
I think people would like to have free scrolling as feature_so I don't like the workaround
Is there anywhere I can read (besides the code) why the design is like that?

**Comment by imsnif** [comment]
> I think people would like to have free scrolling as feature, so I don't like the workaround

I'm with you on that one.

> Is there anywhere I can read (besides the code) why the design is like that?

So, what's happening (in a bit of a simplified way): We keep all the lines inside the terminal pane "viewport" inside a vector. Something like: `Vec<Line>`. We keep the "lines_above" and "lines_below" in something similar. Also a `Vec<Line>`. We scroll by moving lines between them. eg. scroll up one line is taking the last line from "lines_above" placing it at the beginning of "viewport" and then taking the last line of "viewport" and placing it at the beginning of "lines_below".
If new instructions come to the terminal (eg. go to this line and print that character), they need to reset the viewport so that the update will be correct - and unfortunately because of that, they also reset the scroll.
A better solution of course would be to have the scroll be independent of the viewport. Maybe even to only keep an index of it and then know to only display those lines, while updating the state from below.
This is however not a trivial solution to implement. That's because there's another piece of the puzzle here: line wrapping. When we need to wrap lines because the terminal window was resized, we can't do that on the entire scrollback buffer (that can potentially be 10K lines long!) so we have to only do that on the viewport. The actual viewport and the one in the scroll. So for consistency, we'll have to do that to all lines in between too. And there's a host of more issues that stem from this - but this is the gist.
I hope this makes sense, and that I did not ramble on too much. :) This is a part of the code that I personally struggled with and refactored about 4-5 times over the past 6 months. If this is something you're interested in tackling, that would be really cool and I'd be happy to try to give whatever guidance I can.
