### ISSUE TITLE
Tying a terminal command with zellij shortcut

### ISSUE THREAD

**Issue by sprime-team** [zellij-org/zellij#3063]
I use helix editor btw so for opening a new `pane` or `tab` with specific file, first I do `Ctrl+p n` for new pane and then type `hx .` then I have to search for the file. Instead we can do `Ctrl+p N` for doing that directly and then we can type out the name of the file in fuzzy finder

**Comment by cristiand391** [comment]
you can do that by creating a new keybind using the `Run` action:
https://zellij.dev/documentation/keybindings-possible-actions#run

here's an example using `Alt n` to open fzf -> nvim:
```kdl
...
    bind "Alt n" {
      Run "zsh" "-i" "-c" "nf" {
        cwd "/home/cristiand391/code/gh/zellij"
      }
    }
...
```

[zellij-keybind-run-example.webm](https://github.com/zellij-org/zellij/assets/6853656/c4332d19-4826-4aa5-a671-3e5d03d213da)


so I have to call it through zsh because `nf` is shell alias, this exactly:
```
nf='fzf --preview "bat {} --style numbers --color always" --height 90% --multi
--bind "enter:become(nvim -p {+})"'
```

this uses fzf's `become` action the fzf process into nvim (you do that with hx :)):
https://github.com/junegunn/fzf/#turning-into-a-different-process

**Comment by sprime-team** [comment]
thanks for you reply!!
`bind "m" { NewTab; Run "hx" "."; SwitchFocus; CloseFocus; SwitchToMode "Normal"; }`
I did this under tab mode, is there any easier way to do it?

**Comment by cristiand391** [comment]
oh right, the `NewTab` will create a one pane then `Run` will open helix in another one.

You could create a layout like this:
```kdl
layout {
  pane  {
    command "hx"
    args "."
  }
}
```

then do:
```kdl
bind "m" {
  NewTab {
    layout "/path/to/layout.kdl"  
  }
}
```

the new tab will only contain one pane with helix.

**Comment by sprime-team** [comment]
oh this works great!! nice
