### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by cswinter** [zellij-org/zellij#307]
Just saw this on r/rust and tried it out. It looks very nifty, I think I might just ditch tmux now after using it for years!
Couple of questions:
- Is there a way to capture mouse wheel input so it scrolls the zellij pane rather than the outer terminal? Maybe this is difficult to implement, but I seem to recall that this is possible if somewhat painful to set up in tmux, if there was an easy way to enable this in zellij that would be a big win.
- When using windows terminal with the default font the arrow symbols don't render, what font do you recommend? Tools like powerlevel10k mention font installation in the readme (https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k), might be helpful to add a similar section to the zellij readme
- In tmux you can tell which of two side-by-side panes is active by looking at the color of the divider line (either the top-half or bottom-half is colored). zellij doesn't seem to have a visual indicator on what pane you are on beyond the curser (which won't always exist). It would be nice to implement some visual indicator, either the way tmux does or perhaps you can come up with something even better that doesn't require you to remember whether top-half colored means left or right. Maybe changing some of the chars used for the divider line to "point" to the active pane.

**Comment by matu3ba** [comment]
@cswinter Please change the title accordingly to "question: usage"

I also have questions:

1. Why is quitting possible in every mode on simple "q"? That a big bummer, when one mistypes and ideally should be an extra keycombination like in tmux.
2. Why is there no reset counter for the mode (ideally indicating that it requires configuration so be like 3 seconds or longer)?
3. Where is the help or information about active panes/tabs/sessions?
4. Is there a specific reason why <C-c> is not mapped to escape for getting into default view/type mode?

**Comment by imsnif** [comment]
> Just saw this on r/rust and tried it out. It looks very nifty, I think I might just ditch tmux now after using it for years!

That is heartening to hear! :)

>     * Is there a way to capture mouse wheel input so it scrolls the zellij pane rather than the outer terminal? Maybe this is difficult to implement, but I seem to recall that this is possible if somewhat painful to set up in tmux, if there was an easy way to enable this in zellij that would be a big win.

Not yet, but there definitely will be: https://github.com/zellij-org/zellij/issues/175

>     * When using windows terminal with the default font the arrow symbols don't render, what font do you recommend? Tools like powerlevel10k mention font installation in the readme (https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k), might be helpful to add a similar section to the zellij readme

I think a little bit after you opened this issue, @a-kenji did just that: https://zellij.dev/documentation/compatibility.html

>     * In tmux you can tell which of two side-by-side panes is active by looking at the color of the divider line (either the top-half or bottom-half is colored). zellij doesn't seem to have a visual indicator on what pane you are on beyond the curser (which won't always exist). It would be nice to implement some visual indicator, either the way tmux does or perhaps you can come up with something even better that doesn't require you to remember whether top-half colored means left or right. Maybe changing some of the chars used for the divider line to "point" to the active pane.

Zellij has a visual indicator which you can see when there are more than 2 panes... but as you say, when there are 2 it's hard to figure out which is focused. Tbh I don't really like the way tmux does it. Like you mentioned, it forces you to remember which is which and you kind of have to switch a few times to figure it out anyway. I'm not sure what I think about changing the border characters, because that can also be not super intuitive (especially since this is the first pane border a new user sees when they open their first pane).

I have this idea of allowing to layout panes as boxes which I think can address this: https://github.com/zellij-org/zellij/issues/173
What do you think?



> @cswinter Please change the title accordingly to "question: usage"

I personally don't mind the title as it is.

>     1. Why is quitting possible in every mode on simple "q"? That a big bummer, when one mistypes and ideally should be an extra keycombination like in tmux.

I just tested and for me this only happens in tab mode (which is definitely a bug!) - thanks for pointing this out. Would you be interested in issuing a fix for this?

>     2. Why is there no reset counter for the mode (ideally indicating that it requires configuration so be like 3 seconds or longer)?

Hmm... I'm not wild about this ux personally. I like the tool staying in whatever mode I tell it to (especially since there's a clear visual indication of this most times) until I tell it otherwise. I wouldn't mind adding it as a configurable option though.

>     3. Where is the help or information about active panes/tabs/sessions?

I'm not sure what you mean?

>     4. Is there a specific reason why  is not mapped to escape for getting into default view/type mode? Neovim has this as default, which is relative practical.

I agree it's very useful! You can press ESC to go from any mode (except locked) back to normal. It's not written in the help in order not to clutter it.

**Comment by NuSkooler** [comment]
On the issue of quitting, the default config makes it impossible to use modern tools such as `micro` where CTRL-Q is how you quit out of that -- instead we bail from Zellij.

But I concur: Overall this is going to rend up replacing my Byobu usage I think.

**Comment by a-kenji** [comment]
Thanks for the kind words and helpful questions!
I will close it now. Things that are not addressed here have their own issues now.
