### ISSUE TITLE
The experience when switching panes is inconsistant in regard to having to first select the pane by pressing enter to make it the current pane.

### ISSUE THREAD

**Issue by jeffschwartz** [zellij-org/zellij#3070]
When using Alt + to switch panes, the pane that is switched to is made the current pane (shows green border).

When using Ctrl+p to switch panes, the pane switched to is not made the current pane (shows red border) and you have to press enter to make it the current pane.

Not sure if this is intentional but if it isn't can this be standardized to do one or the other for both methods?

**Comment by imsnif** [comment]
So, while I understand your point about standardization one way or another, the rationale here is that with `Ctrl p` + `p` - you don't want to drop back to `Normal` mode from `Pane` mode after each switch, since you're likely to perform this action more than once. With `Alt`, this is not an issue since you always stay in `Normal` mode.

That being said, you can change this behavior by adjusting the keybindings, specifically here by adding `SwitchToMode "Normal"` to the action: https://github.com/zellij-org/zellij/blob/main/zellij-utils/assets/config/default.kdl#L29

More information about keybindings: https://zellij.dev/documentation/keybindings.html

**Comment by jeffschwartz** [comment]
@imsnif thank you for your speedy reply. I honestly didn't know that I could apply configuration to achieve this. I am a recent newbie to Zellij and quite honestly I haven't even begun to tap into all its features yet. Had I know about being able to accomplish this via configuration I'd never have posted this so please accept my apologies. To you and to all the good folks behind this project I just want to say thank you. Zellij is really kind of awesome.
