### ISSUE TITLE
Extending Session CLI (create & switch)

### ISSUE THREAD

**Issue by joshmedeski** [zellij-org/zellij#3081]
I have [created a workflow](https://github.com/joshmedeski/sesh) that makes it really efficient to create and switch to sessions. It's current implementation is in tmux, but I really want to try out Zellij.

Here's what would need to exist in Zellij in order to implement this workflow:
1. `zellij create-session {name}` (ability to make a new session with the cli)
2. `zellij switch-session {name}` (ability to switch the current zellij server to a specified session with the cli)

After these two CLIs are supported it would be trivial to implement a smarter session manager. I'd be open to contributing so let me know if you're interested in these CLI commands.

**Comment by imsnif** [comment]
What's wrong with the current session-manager?

**Comment by joshmedeski** [comment]
I want to quickly create sessions based on projects, right now it's just randomized session names and you have to manually CD into the folder you want.

**Comment by joshmedeski** [comment]
Okay thanks for clarifying the progress here.

Here's a brief summary of the workflow:
https://www.youtube.com/watch?v=l_TTxc0AcCw

I probably won't give Zellij a chance until I'm able to connect and switch to sessions more efficiently. So I'll be keeping track of the plugin process. Or perhaps my video will give you inspiration for improving the built-in session manager.

**Comment by imsnif** [comment]
Please user whichever software makes you happy. :)

Closing this issue for now.

**Comment by mahume** [comment]
Agree with @joshmedeski. In my Kitty config I `send_text` to perform Tmux operations like switch tab and switch sessions and have them remapped to command + Vim directions hjkl. It makes it easy to switch tabs and sessions. This also works in Zellij for switching tabs thanks to the Tmux mode, but it would be nice to switch through the sessions in the same way. The reason I can see it being useful is because it seems like you have to lock the entire session to use Vim properly. If you have multiple tabs open with running servers and Vim open, there is a constant switching between locking and unlocking. Maybe having 1 unlocked session with servers, and 1 locked session with the ability to quickly switch between them would improve usability.

**Comment by imsnif** [comment]
Hi - to all those who are wondering: this behavior is now built-in (switching sessions with specific folders and specific layouts). It's also part of the plugin API, so if you want to do this atomically like @joshmedeski demonstrated, writing a plugin for this should be trivial (you can start by forking the `session-manager` if you like).

More info in the screencast: https://zellij.dev/tutorials/session-management/

**Comment by mahume** [comment]
Reading some of these threads. So an implementation of something like `go-to-previous-session` or `go-to-next-session` won't be possible due to limitations of "true multiplayer support"? At least without forking `session-manager` into a custom plugin. 

Side note. Enjoyed the video format for feature presentations.

**Comment by roberte777** [comment]
> Hi - to all those who are wondering: this behavior is now built-in (switching sessions with specific folders and specific layouts). It's also part of the plugin API, so if you want to do this atomically like @joshmedeski demonstrated, writing a plugin for this should be trivial (you can start by forking the `session-manager` if you like).
> 
> 
> 
> More info in the screencast: https://zellij.dev/tutorials/session-management/

Hey there, I'm interested in writing a plugin for this. Specifically, I'm interested in the exact functionality @joshmedeski has implemented for tmux with his integration with zoxide. I've got a start going, with [this command line utility](https://github.com/roberte777/zesh). However, the main blocker is switching sessions, which I will need a plugin for. 

My main issue is, I'm not interested in a GUI like the session manager provides. I think many people have an interest in Zellij because it provides a lot of the function of tmux, but with better documentation and configuration for keybinds / functionality. However, things like the help menu and session manager GUIs are the type of thing I try to avoid. 

So, zesh works from outside of an active Zellij session. What I'm looking for is a way to support this, plus additionally letting me run the same cli command to switch if I'm already in a session. My understanding is a plugin would not support this? Mainly because I'm unsure from the documentation if the plugin support allows me to extend the Zellij cli, which I think is what would be required to get this to work. 

Essentially, my goal is to allow me to run something like "zesh cn foo" that will open a Zellij session in whatever project zoxide matches with "foo", from outside a Zellij session, or switch me to another Zellij session if I'm already in one. 

If I have to manually look at the Zellij sessions, detect if I'm in one, detach, and then reattach in order to make this work, I will... but I'm hoping there's a better solution.

**Comment by imsnif** [comment]
You can take a look at the switch session plugin API (https://docs.rs/zellij-tile/latest/zellij_tile/shim/fn.switch_session.html) which lets you essentially do an `attach --create` for a session. You can also get the current session name from the `ModeUpdate` event (https://docs.rs/zellij-tile/latest/zellij_tile/prelude/struct.ModeInfo.html).

In order to trigger this from the CLI without rendering any UI, you can use pipes (https://zellij.dev/documentation/plugin-pipes.html) which will also allow you to have the plugin launched if it is not running and then receive the pipe message (which will contain your desired session name).

The only piece of the puzzle that isn't solvable through the CLI is getting the client id. As opposed to tmux, Zellij is a true multiplayer application - meaning that the difference between different clients connecting to the same session is meaningful (they can be focused on different panes/surfaces and have different cursors, their plugins render differently, etc). Since the shell is not aware of this difference, you will not know which client to detach. If you're in a single user session, this is not an issue, but if you're in a multi-user session, you'll have to somehow make this decision. IMO there's no good UX for this in the latter case, which is why Zellij does not support this functionality through the CLI natively. But as a plugin author you can of course do whatever you like (eg. just the first client and hope for the best, all clients focused on the relevant pane, etc.)

If you want to learn more about plugin development, you can take a look at the screencast/tutorial: https://zellij.dev/tutorials/developing-a-rust-plugin/

If you want support, the best place to get it is on our discord (plenty of plugin authors hang out there).

If you end up writing a plugin and want to let others know about it, it would be cool if you wanted to add it to `awesome-zellij`: https://github.com/zellij-org/awesome-zellij

Happy hacking!

**Comment by roberte777** [comment]
> You can take a look at the switch session plugin API (https://docs.rs/zellij-tile/latest/zellij_tile/shim/fn.switch_session.html) which lets you essentially do an `attach --create` for a session. You can also get the current session name from the `ModeUpdate` event (https://docs.rs/zellij-tile/latest/zellij_tile/prelude/struct.ModeInfo.html).
> 
> In order to trigger this from the CLI without rendering any UI, you can use pipes (https://zellij.dev/documentation/plugin-pipes.html) which will also allow you to have the plugin launched if it is not running and then receive the pipe message (which will contain your desired session name).
> 
> The only piece of the puzzle that isn't solvable through the CLI is getting the client id. As opposed to tmux, Zellij is a true multiplayer application - meaning that the difference between different clients connecting to the same session is meaningful (they can be focused on different panes/surfaces and have different cursors, their plugins render differently, etc). Since the shell is not aware of this difference, you will not know which client to detach. If you're in a single user session, this is not an issue, but if you're in a multi-user session, you'll have to somehow make this decision. IMO there's no good UX for this in the latter case, which is why Zellij does not support this functionality through the CLI natively. But as a plugin author you can of course do whatever you like (eg. just the first client and hope for the best, all clients focused on the relevant pane, etc.)
> 
> If you want to learn more about plugin development, you can take a look at the screencast/tutorial: https://zellij.dev/tutorials/developing-a-rust-plugin/
> 
> If you want support, the best place to get it is on our discord (plenty of plugin authors hang out there).
> 
> If you end up writing a plugin and want to let others know about it, it would be cool if you wanted to add it to `awesome-zellij`: https://github.com/zellij-org/awesome-zellij
> 
> Happy hacking!

Thanks for all these resources! Based on your response, I wonder then if the correct solution really is to just run `zellij ls` behind the scenes, check if one of the session is marked as current, and detach if so before running the command to start a new session. Will be exploring this, hopefully something cool comes of it. 

Thanks again!

**Comment by imsnif** [comment]
> Thanks for all these resources! Based on your response, I wonder then if the correct solution really is to just run `zellij ls` behind the scenes, check if one of the session is marked as current, and detach if so before running the command to start a new session. Will be exploring this, hopefully something cool comes of it.

Sure thing. You *can*, but plugins also get this info on change (and on startup) from the `SessionInfo` Event, so no need to instantiate a shell.
