### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by dougg0k** [zellij-org/zellij#3162]
Hi,

I am using a combination where alacritty starts zellij, zellij starts nushell and nushell starts starship, zoxide, atuin and carapace. 

Zellij are somewhat slow when starting, taking about 1-2sec, if I start typing as I open alacritty, it cuts the text till it's fully initialized.

Where if I change alacritty to start nushell, that goes instantly.

Anything that can be done?

Not sure what kind of information would be useful to include on this, if any. I have a very good desktop hardware, so that is surely not the bottleneck.

**Comment by imsnif** [comment]
Try clearing the cache folder (on linux it's `~/.cache/zellij`, I don't have the mac location offhand, but it should be the system default). I plan on issuing a fix for this in the next version.

**Comment by dougg0k** [comment]
Much faster now. Thanks.

But now reappared an old issue that is fixable by pressing Ctrl++ and Ctrl+- after to be in the right size. It was fixed, maybe due to cache after many Ctrl++.

![2024-02-28_10-07](https://github.com/zellij-org/zellij/assets/10801221/1eb84f2d-783c-4b49-ac7f-b0e3dd742b00)

**Comment by dougg0k** [comment]
In Wezterm, it seems to have an almost similar issue, but after a command, it auto fixes.

That is a datetime information from starship, but, it's the same initial pattern from the smaller pane.

![2024-02-28_12-12](https://github.com/zellij-org/zellij/assets/10801221/86d82c00-54f3-4f55-99ad-cfb709ef61d6)

**Comment by imsnif** [comment]
> Any idea what could be causing it? @imsnif

Friend - respectfully, this issue was originally about "slow startup". I gave a quick answer because I had one and didn't want you to wait. I unfortunately do not have the capacity to provide support in this fashion to every user for all the issues in their environment.

Please look through the issues and see if something like this comes up, if you don't find one and have a reproducible recreation you are welcome to open a new issue and follow the issue template, and in any case - you are more than welcome to ask for support in one of our chat platforms.

**Comment by dougg0k** [comment]
Make sense.

**Comment by dougg0k** [comment]
Just to leave here on why this happens as I found out, it seems that zellij does not take the `startup_mode` into account, mine was set to start `Maximized`.
