### ISSUE TITLE
In sequence keybinding

### ISSUE THREAD

**Issue by mikoloism** [zellij-org/zellij#3201]
What if we can bind sequence keys to doing things?

For example `crtl p` then `s` will be do same thing of `ctrl n` will do (to resize panes, and the `ctrl n` will be free to default binding usage)

Something same in vscode via `ctrl k` then `m` do change language mode

The benefits are merging keys and voiding conflicts

**Comment by mikoloism** [comment]
But I know and I understand this makes break changes and take long time to supporting

**Comment by rsniezek** [comment]
you can already do that with if the first part of the sequence puts you in a mode, like pane mode or tab mode. your example 

> For example crtl p then s will be do same thing of ctrl n

can be achieved with 
`
    pane {
        bind "s" { SwitchToMode "Resize"; }
    }
`
since ctrl + p puts you in "pane" mode, then "s" will put you in resize mode. 

Anyway, having something more generic, like "virtual modes" that can be bound to keybinding would be very powerful indeed. This way we could define some virtual mode names that don't correspond to any of the actual zellij modes, and this way we could bind sequences of key strokes to some actions. Or maybe there  is easier way to do that already, I don't know :) 

but something like:
`
shared_except "locked" {
    bind "ctrl v" { SwitchToMode "my_virtual_mode"; }
}

my_virtual_mode {
    bind "n" { SwitchToMode "my_virtual_mode_two"; }
}

my_virtual_mode_two {
    bind "c" { CloseFocus; }
}
`
would make a sequence of ctrl + v, n, c do the focus close action.

**Comment by mikoloism** [comment]
The "Virtual Mode" is cool, and answer to the question, thanks :heart:
