### ISSUE TITLE
Takes long on Ctrl-R

### ISSUE THREAD

**Issue by matthiasbeyer** [zellij-org/zellij#325]
I use the `fzf` bash plugin that helps me searching the history with fuzzy matching.

When I fire up zellij and hit `Ctrl-G` to lock and then `Ctrl-R`it seems to take very long until the fuzzy-selection appears. That might be because it is not rendered properly, I'm not sure.

I tested this with bash 4.4 and both Konsole and alacritty.

**Comment by a-kenji** [comment]
Thank you! That could have a lot of interactions.
One notable could be unhandled sequences.

If you want you can
`zellij --debug` and then run your programs, and look in
`cat /tmp/zellij/zellij-log/log.txt` and see if there is output there.
If there is please send us the file.

**Comment by SimonMonecke** [comment]
I have the problem with fzf, alacritty and zellij. Here is the complete debug file after `<ctrl><g>, <ctrl><r>, <ctrl><g>, <ctrl><q>`
```
Unhandled csi: n->[6]
```

**Comment by imsnif** [comment]
Could you check with version 0.9.0 please?

**Comment by matthiasbeyer** [comment]
Issue still exists.

**Comment by imsnif** [comment]
This is fixed in `0.10.0`. fzf was sending a CPR (https://vt100.net/docs/vt510-rm/CPR.html) to Zellij, which it was ignoring and so it hung until it got a timeout. This now works well for me in both bash and fish.

I'm closing this issue, but if you're reproducing it in `0.10.0` or beyond, please tag me and I'll re-open.

**Comment by sstadick** [comment]
Post update this is working for me! Thanks for fixing this, this was the only major painpoint :+1:
