### ISSUE TITLE
weird question mark

### ISSUE THREAD

**Issue by lifesign** [zellij-org/zellij#330]
Got this weird question mark
![image](https://user-images.githubusercontent.com/2189610/115806646-c0c1dc00-a419-11eb-8f25-53d2c40ff551.png)
MacOS Big Sur: 11.2.3
Iterm2: Build 3.4.1

**Comment by a-kenji** [comment]
Thank you for the report! That is caused by a missing unicode character in your font, quite a few people are having similar problems, so we are thinking about a temporary solution, untill we find a more permanent one.

If you figure out how to install the nerdfonts on mac, it should show correctly:
https://zellij.dev/documentation/compatibility.html

Related #313 .

If you do get the fonts installed and working I would be interested to hear about that!

**Comment by a-kenji** [comment]
@lifesign 

You can now request zellij to start with a more compatible ui through
`zellij options --simplified-ui` or binding `simplified_ui: true` in the 
configuration file.

Thank you for the report!
And please do reach out again if you have any more issues
down the line.
