### ISSUE TITLE
Release strategy?

### ISSUE THREAD

**Issue by matthiasbeyer** [zellij-org/zellij#332]
Please note: right now, the releases are in 0.x.y, so **all of this is more or less nit-picking**! But I fear that if we cannot get it properly done now, we cannot after 1.x.y and that would result in a mess for packaging people and possibly a lot of confusion.

---

So, there are three tags in the repository right now:

* `v0.1.0-alpha`
* `v0.5.0-beta`
* `v0.5.1`

The following tags are missing in the repository, given that `0.5.1` is the latest release:

* `v0.1.0`
* `v0.2.0`
* `v0.3.0`
* `v0.4.0`
* `v0.5.0`

And if you think `v0.5.0-beta` is `v0.5.0` (which [it is not](https://semver.org/#spec-item-11)), then `v0.5.1` [broke semver](https://semver.org/#spec-item-6) to `v0.5.0(-beta)` because it changed a user interface (CLI).

I know that [semver says](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase) that in 0.x.y you can do anything you like, **as said: this is very much nitpicking here**. I really don't want to anger you with this issue and I do not want to finger-point to anyone here! But please try to get it right, because that's just a piece of cleanness one should be able to expect!

**Comment by imsnif** [comment]
Hey, thanks for pointing this out! You're not angering anyone. :)

Before the beta we didn't really pay much attention to the release because things were kind of chaotic (even more than they are now). That's why all those tags are missing. You are very right about needing order in this after 1.0. We are definitely taking liberties because of the pre-1 semver rule :)

There's quite a few contracts that Zellij has that we need to keep an eye on: the CLI interface (which you pointed out), the keybindings (in case someone wants to automate stuff), the plugin API, the configuration file format, etc. So I guess this is kind of a work in progress.

Personally, I believe semver is a lie and that every change is a breaking change for someone. But I definitely want us to try to do our best here!

**Comment by matthiasbeyer** [comment]
Yeah, a good idea would be to maybe only update the minor version (so `0.6.0`, `0.7.0`, ...) until there is some reasonable agreement in the community that `1.0.0` is ready. :smile:

**Comment by imsnif** [comment]
Thanks for the tip! Let's try to do that.

**Comment by raphCode** [comment]
can we close this or is it still relevant?
