### ISSUE TITLE
Incorrect MSRV

### ISSUE THREAD

**Issue by kxt** [zellij-org/zellij#3476]
Cargo.toml specifies `rust-version = 1.60`, which is wrong:
- rust-toolchain.toml has the toolchain pinned to 1.75
- dependencies like wasmtime has an MSRV of 1.75

There are a few ways to fix this discrepancy:
- remove `rust-version` from Cargo.toml
- remove `channel` from rust-toolchain.toml and set `rust-version = 1.75` in Cargo.toml
- update `rust-version` to 1.75, and cross our fingers that it will stay in sync with `channel` in the future  

By looking at the commit logs I couldn't figure out the reason for pinning it to one specific version in rust-toolchain.toml, so I recommend bumping `rust-version` in Cargo.toml to 1.75 and removing `channel` from rust-toolchain.toml.

@har7an

**Comment by har7an** [comment]
Hi @kxt,

thanks for pointing this out! I wasn't aware we populate that field when I updated the rust toolchain versions. Since the `rust-version` in `Cargo.toml` seems to be more of a "hint", I'll remove it and stick with `rust-toolchain.toml`, the reason being: [Cargo respects this file when compiling][1] so it will ensure the mentioned toolchain is installed and used for all cargo commands.

The reason we're pinning the rust version is to remove a "point of failure" during development: The rust version changes only when we ask it to, so new bugs that crop up during regular development should only originate from the individual crates or the code we've written ourselves. This will be fixed with #3480.

[1]: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
