### ISSUE TITLE
Changing the keybindings for plugins like session-manager

### ISSUE THREAD

**Issue by AlexanderWatts** [zellij-org/zellij#3485]
Is there a way that the keybindings for a plugin like `session-manager` can be customised like the bindings for different modes? For example, in the session-manager I'd like to delete a single session by doing Ctrl-x instead of Del which does not exist on my keyboard.

I believe these are fixed from looking at `https://github.com/zellij-org/zellij/blob/main/default-plugins/session-manager/src/main.rs` lines 338

```rust
BareKey::Delete if key.has_no_modifiers() => {
    if let Some(selected_session_name) = self.sessions.get_selected_session_name() {
        kill_sessions(&[selected_session_name]);
        self.reset_selected_index();
        self.search_term.clear();
        self.sessions
            .update_search_term(&self.search_term, &self.colors);
    } else {
        self.show_error("Must select session before killing it.");
    }
    should_render = true;
},
BareKey::Char('d') if key.has_modifiers(&[KeyModifier::Ctrl]) => {
    let all_other_sessions = self.sessions.all_other_sessions();
    if all_other_sessions.is_empty() {
        self.show_error("No other sessions to kill. Quit to kill the current one.");
    } else {
        self.show_kill_all_sessions_warning = true;
    }
    should_render = true;
},
BareKey::Char('x') if key.has_modifiers(&[KeyModifier::Ctrl]) => {
    disconnect_other_clients()
},
```
I think it'd be super useful if these could be set via the config something like...

```
    session {
        bind "Ctrl o" { SwitchToMode "Normal"; }
        bind "Ctrl s" { SwitchToMode "Scroll"; }
        bind "d" { Detach; }
        bind "w" {
            LaunchOrFocusPlugin "session-manager" {
                floating true
                move_to_focused_tab true
                keybinds {
		    bind "x" { Delete; }
		}
            };
            SwitchToMode "Normal"
        }
    }
```

**Comment by imsnif** [comment]
The best way to change these bindings is by forking the plugins and either changing the hard-coded bindings or creating a plugin that offers this config option.

These are not provided as a built-in option in order to help alleviate the burden of maintenance, while still allowing users the option to customize these if they like (albeit with a little more effort).

**Comment by AlexanderWatts** [comment]
@imsnif thanks for the response, I will update these values by forking the plugin much appreciated 🙌

**Comment by nov1n** [comment]
> @imsnif thanks for the response, I will update these values by forking the plugin much appreciated 🙌

@AlexanderWatts Are you planning to make these values configurable from the keymap file as you suggested? I think there are more people interested in this (including me). If not, I'll have a look myself.

**Comment by imsnif** [comment]
If one of you (or anyone else ofc) makes a configurable plugin out of this, we'd be happy to link to it in [awesome-zellij](https://github.com/zellij-org/awesome-zellij).

**Comment by AlexanderWatts** [comment]
Heya @nov1n I can certainly have a look 😀 I was able to update the bindings manually and will look at getting those options from the config which you can see in `zellij-utils/src/kdl/mod.rs`

**Comment by nov1n** [comment]
Very nice! Let me know when you have something usable.

**Comment by comatory** [comment]
👋 Hey, hate to resurrect closed issue, but I figured it's best to ask here, instead of creating a new one.

_This is just a friendly question because I'm curious:_ why don't this part of `zellij` support custom key bindings?

I guess I'm one of those folks that are switchers from `tmux`[^1] which has really nice session floating window, which shows previews of terminal and provides a tree-like navigation. To me it feels very unnatural to suddenly move my hand to use arrow keys when trying to attach to different session.

I don't feel confident writing Rust code, otherwise I'd try and contribute to some kind of customization. Perhaps, there's already a plugin that I could use to re-create the tmux experience.

[^1]: By the way, I'm not trying to bend `zellij` into `tmux`. I'm trying to get used to slightly different concepts and muscle memory fights back hard 😅  So I'm OK with some compromises.

**Comment by yangwao** [comment]
Hello, I found this old issue, and I would like **remove** binding on Ctrl-D in the session manager to kill all session as I lost <1 hour resurrecting my sessions. Docs say there should be some dialog, but I did not see any to confirm lol
