### ISSUE TITLE
Panic in `Grid::scroll_down_one_line`: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by ForsakenHarmony** [zellij-org/zellij#3525]
## Issue description

```
Error occurred in server:

  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │     1. stdin_handler_thread: AcceptInput
  │     2. screen_thread: ScrollDownAt
  │
  ├─▶ At zellij-server/src/panes/grid.rs:702:71
  ╰─▶ called `Option::unwrap()` on a `None` value
```

https://github.com/zellij-org/zellij/blob/cd0cc06cec039623a55273cdc089bdde613e88e7/zellij-server/src/panes/grid.rs#L702

## Minimal reproduction

Can reproduce only it locally with some specific output from ripgrep.

Run:
```
rg "something"
clear
```
After that, scroll up all the way and scroll down again

## Other relevant information

```
❯ zellij --version
zellij 0.40.1
```

## Suggestion

Should probably remove all calls to `.unwrap()` in the codebase.

Ideally, handle it gracefully or at least turn them into `.expect("reason")` calls with a description.

**Comment by practicalrs** [comment]
I have the same problem

```
Error occurred in server:

  × Thread 'screen' panicked.
  ├─▶ Originating Thread(s)
  │     1. stdin_handler_thread: AcceptInput
  │     2. screen_thread: ChangeMode
  │
  ├─▶ At /home/michal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zellij-server-0.40.1/src/panes/grid.rs:702:71
  ╰─▶ called `Option::unwrap()` on a `None` value
  help: If you are seeing this message, it means that something went wrong.

        -> To get additional information, check the log at: /tmp/zellij-1000/zellij-log/zellij.log
        -> To see a backtrace next time, reproduce the error with: RUST_BACKTRACE=1 zellij [...]
        -> To help us fix this, please open an issue: https://github.com/zellij-org/zellij/issues

```

I'll try to repeat it later

**Comment by imsnif** [comment]
Thanks for the report! I issued a fix for this in the linked PR. I get why this was hard to reproduce, it's very much an edge-case that was only made possible by recent changes in that area.

As for the suggestion - calls to unwrap in this area represent situations that should not happen and should have ideally been caught by the tests. Over the years some of them became possible due to algorithm changes and insufficient pairs of eyes for thorough reviews or code maintenance. This is a symptom of a very old and legacy part of the code-base that I very much want to replace or re-write. Hopefully the gods will grant me the capacity to do so at some point.

For now, I once again appreciate the report.

**Comment by ForsakenHarmony** [comment]
I'll close this for now and hope it doesn't come back
