### ISSUE TITLE
Show date time and host name in the status bar as tmux by default?

### ISSUE THREAD

**Issue by hiyyg** [zellij-org/zellij#3537]

**Comment by giyany** [comment]
Requests for "the feature that I like from tmux" are not resolved for two reasons.
1, zellij is not a tmux clone and doesn't aspire to be one. Replicating tmux features is not a priority. Zellij is not tmux.
2, we genuinely don't know what you mean when you say "feature x from tmux", because many of us don't use tmux and certainly don't know many of its features.

If you're interested in promoting this topic, please consider explaining what you're trying to do and what you wish to see. In many cases, zellij offers features that can help you achieve it, albeit often with with a different workflow.

**Comment by giyany** [comment]
In addition, we ask to follow the issue template for a reason.

**Comment by hiyyg** [comment]
Thanks. I will use tmux.

**Comment by Zykino** [comment]
Note there are community provided plugins bars. As I explained on discord:

[zjstatus](https://github.com/dj95/zjstatus) it is fully customizable and have an extensive config. (It is the oldest of the 2, and the most known/talked about)
[zj-status-bar](https://github.com/cristiand391/zj-status-bar/) is an opinionated fork of the compact bar with fullscreen pane indicator, tab index and some others visuals changes. The only configuration is the one inherited from the base compact plugin.

There may be others, that I’m not aware, check the lists https://github.com/zellij-org/awesome-zellij and https://zellij.dev/documentation/plugin-examples.html. And since community plugins exist you can always fork one (official/community/create a new) to suits your specifics needs.
