### ISSUE TITLE
Tip/hint disappear when entering a mode

### ISSUE THREAD

**Issue by jlimas** [zellij-org/zellij#3549]
## Issue description
Using the ~HEAD version of Zellij when I enter a mode the hint/tip row doesn't show anything.
## Minimal reproduction

This is the normal mode.
![image](https://github.com/user-attachments/assets/a7a0d62a-c760-41a9-9fd9-ffaa6441cdcc)

This is as soon as I pressed `Ctrl + p` nothing is showing in the status-bar.
![image](https://github.com/user-attachments/assets/dbed5f0d-2fd1-4d8c-803e-418972cd45da)

## Other relevant information
Using this layout but I already tried with borderless true and size 1 and 2.
```
layout {
    pane size=1 borderless=true {
        plugin location="tab-bar"
    }
    pane
    pane size=5 borderless=false {
        plugin location="status-bar"
    }
}
```

**Comment by giomf** [comment]
I have the same Issue.
When not using the default layout the hints disappears when entering a mode.

**Comment by imsnif** [comment]
This new version includes a UI revamp (will be documented before release). To use the old behavior, you can use the `classic` layout (eg. start with `zellij -l classic`).

Otherwise, the new layout works best when the status bar occupies 1 line instead of 2 (which also gives us more screen real-estate).
