### ISSUE TITLE
display tab index before tab name just like tmux

### ISSUE THREAD

**Issue by MicePilot** [zellij-org/zellij#3591]
I use Alt + Number shortcut keys to quickly switch between TAB. When there are many TAB and modified the TAB name, it is difficult to quickly judge the current of a TAB, which makes the use of shortcut keys not convenient. So can you support the Tab Index before TAB NAME?

**Comment by Jimmyscene** [comment]
I'll let the authors speak to their intentions when they can, but in the meantime, the zjstatus plugin allows you to specify a format for each of the tabs, with one of the options being "{index}", which is the value you're looking for

https://github.com/dj95/zjstatus/wiki/4-%E2%80%90-Widgets#tabs

**Comment by vimkim** [comment]
Thank you so much both of you for bringing up and solving this question

**Comment by mortang2410** [comment]
Hi. I think this issue should be revisited. Having the tab index always available by default is important for easy switching. The tab index is different from the name, and they can't replace each other. Zellij already has an intuitive interface design by default, and the index should be available by default instead of relying on a plugin. See #4179 and #3709. I'm sure other concerns have also been raised over this lack of index. 

It appears that PR #4395 has fixed this issue. I would highly agree with working upon that PR.

**Comment by imadtg** [comment]
> Hi. I think this issue should be revisited. Having the tab index always available by default is important for easy switching. The tab index is different from the name, and they can't replace each other. Zellij already has an intuitive interface design by default, and the index should be available by default instead of relying on a plugin. See [#4179](https://github.com/zellij-org/zellij/pull/4179) and [#3709](https://github.com/zellij-org/zellij/issues/3709). I'm sure other concerns have also been raised over this lack of index.
> 
> It appears that PR [#4395](https://github.com/zellij-org/zellij/pull/4395) has fixed this issue. I would highly agree with working upon that PR.

Second this, this seems like such an essential feature that could benefit so many people.

**Comment by ivoronin** [comment]
For the time being, you can use http://github.com/ivoronin/zellij-tab-bar-indexed/
