### ISSUE TITLE
Keybindings misbehaving on foot with kitty-keyboard-protocol enabled

### ISSUE THREAD

**Issue by tranzystorekk** [zellij-org/zellij#3723]
# Issues with the Zellij UI / behavior / crash

## Issue description

On `foot` terminal, when the KKP is enabled in zellij, keybindings don't work properly.

Issue can be worked around by setting `support_kitty_keyboard_protocol false`

## Minimal reproduction

On `foot`:

```
zellij setup --dump-config > test-config.kdl
zellij -c test-config.kdl
```

then try pressing `Ctrl + g` in particular.

Expected: lock mode toggles

Actual: New prompt line in shell appears, as if pressing `Enter`

## Other relevant information

zellij `0.41.1`
foot `1.19.0`

**Comment by gmr458** [comment]
I'm also experiencing this, the `Alt + []` keyboard shortcut only worked in GNOME Terminal (I tried Alacritty, Kitty and Foot) until I disabled the Kitty Keyboard Protocol.

**Comment by imsnif** [comment]
I don't have access to a machine with Wayland, so can't directly test with foot, but I have issues a fix for similar problems with Kitty itself and just merged it into main. Could you give `main` a try and see if this also fixes the issues with foot?

To try:
1. Clone the `main` branch of this repo
2. Run `cargo x run` in its root

**Comment by tranzystorekk** [comment]
`main` seems to fix the issue for me 😄

**Comment by imsnif** [comment]
Amazing, thanks for testing. I'm going to wait a little bit for other minor stuff and regressions to pile up and will then release a patch.

**Comment by plutack** [comment]
I currently auto start zellij  session manager  with foot on launch. This also messes things for me..I just get panic just trying to use arrow keys to select session, so for now I have resulted to downgrading back to v0.40.1 . 
Also why trying  to use alacritty to identify the problem, before I found this issue, room plugin for tab navigation also was giving panic in trying to navigate, could that be an enter key translation problem as I read something like enter key Is sent rather than /n or something like that
Also please notify us when. A patch is released.
Thanks
