### ISSUE TITLE
Session manager doesn't react on any keys

### ISSUE THREAD

**Issue by estin** [zellij-org/zellij#3756]
Hi! after update to 0.41.1 (arch linux via pacman) popup panes doesn't accept commands

Case

1. start
```
rm -rf  /tmp/zellij-1000
rm -rf ~/.cache/zellij
zellij --debug
```

2. Unlock (locked by default) and open session-manager
Ctrl-g Ctrl-o w

3. Session manager doesn't react on any keys
and all pop-up panes doesn't react too.

<details>
<summary>basic info and logs</summary>

`zellij --version`: `zellij 0.41.1`
`stty size`: `47 240`
`uname -av`:  `Linux archlinux 6.11.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000 x86_64 GNU/Linux`

[zellij.log](https://github.com/user-attachments/files/17697736/zellij.log)

[zellij-22.log](https://github.com/user-attachments/files/17697738/zellij-22.log)

</details>

P.S. I can help to debug it

**Comment by imsnif** [comment]
Does it work without a config? Eg. with `zellij setup --clean`?

**Comment by imsnif** [comment]
Sounds like this is something specific in the config then? I realize the behavior may have changed in the version, but if you'd like to troubleshoot it and find an exact reproduction of what worked in a different way before than now, that would be great.

**Comment by imsnif** [comment]
Zellij only sends keys to the panes running inside it (terminal panes or plugin panes such as the session manager) in `locked` mode and in the base mode (in your case it is also locked). This is a fix from the previous version, I think doing otherwise would be unexpected (because then we'd reach a situation in which in `normal` mode - for example - Zellij would intercept some keys and send the others to the underlying plugin/terminal).

Sounds like you found a fix though, by getting `Ctrl o` + `w` to switch back to `locked` mode, right?
