### ISSUE TITLE
`Alt + Right Arrow` Unexpectedly opens a floating pane on macOS in Zellij v0.41.1

### ISSUE THREAD

**Issue by jpaju** [zellij-org/zellij#3819]
## Issue description
As of Zellij v0.41.1, pressing `Alt + Right Arrow` (`Option + Right Arrow` on macOS) unexpectedly opens a new floating pane. I attempted to unbind this key (unbind "Alt Right"), but the issue persists. Based on WezTerm sends the sequence `\x1bf` when `Alt + Right Arrow` is pressed. The issue occurs even with Zellij’s default configuration.

## Environment
MacOS 14.7.1
WezTerm 20240203-110809-5046fc22
Zellij v0.41.1
Fish 3.7.1

## Minimal reproduction
1. Open zellij (on macOS)
2. Press `Alt` (`Option` key ⌥ on mac) + `right arrow`
3. See new floating pane being opened

## Other relevant information
- Unable to test on other operating systems to determine if this is macOS-specific.
- This behavior was also confirmed using macOS’s built-in Terminal app and zsh, so it seems it's not related to terminal emulator or shell.

**Comment by dreamfliper** [comment]
can be reproduced in 0.41.2 on macOS

**Comment by tlinford** [comment]
With 'enable_kitty_keyboard = true' in my wezterm config don't get this.

**Comment by jpaju** [comment]
For me setting `enable_kitty_keyboard = true` in western configuration doesn't fix it 😔

**Comment by lowfront** [comment]
This issue is also occurring in my Hyper terminal.

macOS 15.1.1

**Comment by lowfront** [comment]
Taking a cue from @jpaju's commants, I ran cat and checked the signals from the left and right arrow keys.
left: `^[[D`, right: `^[[C`
But if we type the arrow keys like Alt, it looks like this
left: `^[b`, right: `^[f`

Meanwhile, on my alt-enabled iTerm2, this is not happening, and when I checked the arrow key signaling, if I press alt and type arrow keys, no arrow key input occurs.
Maybe it's a dumb idea... but considering the floating pane default shortcut is `Alt + F`, I wonder if it's caused by parsing the `ESC + F` sequence incorrectly?

**Comment by lowfront** [comment]
And... if I change the toggle floating pane shortcut `Alt + f` to `Alt + x` in `~/.config/zellij/config.kdl`
the issue of opening the floating pane with Alt + ArrowRight disappears.

**Comment by jpaju** [comment]
Interesting 🤔 For me signals are different:
- Opt + left: `^[[1;3D`
- Opt + right: `^[[1;3C`

Anyways the problem has disappeared for me (with [configuration changes](https://github.com/zellij-org/zellij/issues/3819#issuecomment-2514351608)) so I'll close this issue

**Comment by tgross35** [comment]
Removing my `config.keys` override just makes option+left and option+right switch zellij tabs rather than move one word forward or backward, which isn't the desired behavior. Setting `config.enable_kitty_keyboard = true` doesn't seem to do anything. I can also replicate this with iterm2 that uses a similar mapping.

If anyone has the expected option+L/R behavior of moving by word, would you be able to share your configuration?

Also perhaps this issue should be reopened, a default keybinding that conflicts with `readline` commands is really unfortunate.

For reference, my current Wezterm configuration:

```lua
config.enable_kitty_keyboard = true

config.keys = {
  {
    key = 'LeftArrow',
    mods = 'ALT',
    action = wezterm.action.SendKey {
      key = 'b',
      mods = 'ALT',
    },
  },
  {
    key = 'RightArrow',
    mods = 'ALT',
    action = wezterm.action.SendKey {
      key = 'f',
      mods = 'ALT',
    },
  }
}
```

**Comment by tgross35** [comment]
If anyone else needs it, I was able to fix this by unbinding on Zellij's side:

```kdl
keybindings {
    unbind "Alt f"
}
```

**Comment by smdsbz** [comment]
Tmux took ctrl+b, Zellij then took alt+f. People just hate Emacs editing keys 😆

**Comment by nesl247** [comment]
Can this be reopened given it's a bad experience out of the box for Mac users?

**Comment by extemporalgenome** [comment]
In Ghostty on Mac, this worked for me:

In `~/.config/ghostty/config`, add:
```
keybind = alt+left=unbind
keybind = alt+right=unbind
```

In `~/.inputrc`, add:
```
"\e[1;3C": forward-word
"\e[1;3D": backward-word
```

The `~/.inputrc` change isn't needed for the fish shell or zellij (the ghostty unbinds were enough), but the inputrc does help renable alt+left and alt+right in bash.

The helix editor was also affected by the unbind, but I like the result better (alt+left/alt+right now select whole blocks, which is more powerful than simple cursor navigation).
