### ISSUE TITLE
Feature: Keybind for Returning to Previous Tab:

### ISSUE THREAD

**Issue by SaintFenix** [zellij-org/zellij#398]
As part of #376 I'll be creating issues for missing tmux features for discussion for inclusion in Zellij, or overall improvement if Zellij's equivalent doesn't have as much functionality as Tmux.

This one is fairly simple.

A keybind in which will select the most recent tab you were on before the current one.

Basically Zellij could keep a history of what tabs you were on, and return you to the previous one.

It could be in Normal Mode, or Tab Mode, though I'd imagine it most useful in Normal Mode.

**Comment by sagittarius-a** [comment]
Since it is labelled as a good first issue, I gave it a shot. I have a proof of concept working for this feature.

Before submitting a PR, I'd like to address few points regarding implementation:

- What default keybinding to use ? I've considered `Tab` in Tab mode. If we implement this in Normal mode, what should be the associated keybinding ?
- Do we use a toggle switch, i.e going backing and forth between the two last visited tabs, or we keep a list of visited tabs and we navigate through the list ? I've implemented the former since it felt more intuitive.

Thanks

**Comment by a-kenji** [comment]
Hey @sagittarius-a, that is awesome!

I think `Tab` in Tab mode is a good idea.
I am not sure if it makes much sense to bind it by default in the 
Normal mode, but am open to more input on that.

I also think the former is more intuitive, and also what
most people would expect of such a feature.

Please do feel free to reach out if you have any more questions!

**Comment by sagittarius-a** [comment]
I'm almost ready to submit the PR but unfortunately I have issues regarding the `Tab` mapping. Indeed, it is not available in `termion` so I cannot use it in a keybinding.

I use `z` during the development of the feature since I felt that using `Tab` would require more than a copy paste in the config file.

However, `BackTab` is available, which is equivalent to `Shift + Tab`, which I find quite cumbersome.

What's your opinion on this ?

**Comment by sagittarius-a** [comment]
Alright PR is submitted.

I hope I did not forget something important. Any feedback appreciated :)
