### ISSUE TITLE
i3wm - proportionate adjustment between panes

### ISSUE THREAD

**Issue by muralikodali** [zellij-org/zellij#406]
zellij version is 0.5.1

I am using i3wm as window manager on Arch Linux. 
When i launch a window of other application, this window is proportionately adjusted with other window (i.e terminal (alacritty) with zellij having two panes). Terminal with zellij becomes unusable **with disproportionate adjustment of panes**.

![screenshot_20210429113309_IMGP](https://user-images.githubusercontent.com/11482766/116509314-b2276900-a8e0-11eb-8149-d7cefc11b687.png)

**Comment by imsnif** [comment]
Hey, thanks for reporting this!

I have the same setup as you and also experience this problem. This happens because of our resizing algorithm, and is something we're working on improving in the very near future. We just haven't completely decided how to address this.

For now, sometimes resizing the terminal window back and forth gradually can do the trick. I know this is an imperfect workaround to say the least though...

This will get sorted soon!

**Comment by horasal** [comment]
@imsnif 
Should we make `PositionAndSize`  percent instead of line of row/col?
It requires many changes in `tab.rs` but I think it's worth a try.

**Comment by imsnif** [comment]
> @imsnif
> Should we make `PositionAndSize` record percentage instead of number of characters?
> It requires many changes in `tab.rs` but I think it's worth a try.

That's a super interesting idea! The issue though is that we have a plugin API that allows plugin panes to be set with a fixed max/min width/height (we use these in both the tab bar and the status bar currently). Once we allow those, this becomes a bit of a complex problem.

The ideas we currently have are either to try to solve this in a "UX" way by expanding the layout feature to suit most needs rather than forcing the user to manually build their layouts every time... that way we can reapply the layout on every resize. Or @TheLostLambda is thinking of giving a more involved placement algorithm a try using cassowary.

If you have a different idea @horasal (either building in your percentage suggestion or with something else) it would be very useful to discuss.

**Comment by horasal** [comment]
> a plugin API that allows plugin panes to be set with a fixed max/min width/height

I'm not sure if I cache the point. Here are some thoughts:

1. (based on the percentage solution) put plugin in a "container" pane. let the container transform the width/height between percentage and num of chars. The container can pad empty chars when terminal too wide or cut of some contents when terminal height < min width of plugin
2. record layout as a table &offsets. for example, split down -> split right can be 
  
```
Row1: pane1
Row2: pane2, pane3
```

if user adjust its width/height, we record their incremental diff, e.g. for pane1 height + 10, pane3 width - 10, we have:

```
Row1: pane1(height + 10)
Row2: pane2(height - 10, width - 10), pane3 (height - 10, width + 10)
```

on every terminal resize event, we can calculate the position of panes from this table by

* split panes without incremental differences 
* apply incremental differences on each pane

**Comment by TheLostLambda** [comment]
Fancy new resize is on the way that preserves ratios and can solve (I think) even the most complex of layouts:

https://user-images.githubusercontent.com/6251883/116784821-2eab7a80-aa8e-11eb-8cf8-1c934bfa5b83.mp4

Hopefully this will fix this particular issue!

**Comment by TheLostLambda** [comment]
I'm continuing work on this in #568

There is a decent amount still to do, but we're getting close to solving this issue!

**Comment by TheLostLambda** [comment]
@muralikodali Howdy! In a pleasant surprise, the resize fix was finished before the heat-death of the universe! This problem *should* be fixed on `main` with a release coming soonish :)
