### ISSUE TITLE
Ctrl+Right won't pass through - even on lock mode

### ISSUE THREAD

**Issue by dantepippi** [zellij-org/zellij#420]
When I try to use Ctrl + Right, Zellij won't send those keys to the terminal. Even on lock mode, where I'd expect every key combination except Ctrl + g to pass through, it doesn't work.

I found a related issue (#357) but reporting problems where users could not bind those keys. My problem is related but a little different, where I just want to be able to pass them to other programs. If you guys prefer to keep just one issue, let me know and I  comment there.

`zellij --version`: tested with 0.6.0 and main branch

**Comment by dantepippi** [comment]
Just found out it's probably related to this termion issue. Sad part is that this issue is 1 year old already, so we might need to find another option? 

https://gitlab.redox-os.org/redox-os/termion/-/issues/169

**Comment by a-kenji** [comment]
Thanks for creating this issue! I also believe they are related. We have problems handling the key at all. If it helps people find the issue, i think its OK to keep it.

cc @khs26 
Investigated a bit about this issue. If I recall correctly it works but is still in a very weird state and it is quite some work to implement it cleanly. Maybe he can give additional input.

**Comment by khs26** [comment]
My finding was mainly that the existing PR looked a bit messy. They added a whole bunch of `Ctrl<Special>` options to the existing `Key` enum. I'm not sure if the termion devs would be keen to add that.

I did half try making the `Ctrl(char)` enum into a `Ctrl(dyn CharOrSpecial)` enum, but was foiled by my rubbish knowledge of Rust traits.

**Comment by imsnif** [comment]
@khs26 - do you think we can fix this by either:
1. Forwarding all of these to the pty directly: https://github.com/zellij-org/zellij/blob/main/src/common/input/handler.rs#L74
2. Looping over stdin directly and then trying to interpret the keys with termion rather than using their mixin here: https://github.com/zellij-org/zellij/blob/main/src/common/input/handler.rs#L67
?

I also read somewhere that people have been having issues inserting certain Chinese characters with Shift. I guess this is related? I'm hoping one of these solutions can be a quick fix so that we won't have to have a fully fledged VTE state machine in the input as well :)

**Comment by imsnif** [comment]
@dantepippi - this should be solved in `0.11.0` and onwards. Can you please check?

**Comment by dantepippi** [comment]
Yes @imsnif, this issue seems to be fixed in `0.11.0`.

**Comment by imsnif** [comment]
Awesome :) Thanks for checking
