### ISSUE TITLE
Can't bind Alt+Ctrl+char

### ISSUE THREAD

**Issue by lilyball** [zellij-org/zellij#463]
According to the documentation, I can bind Ctrl keys and Alt keys, but there's no way to bind Ctrl+Alt keys. For example, Alt+h/j/k/l are pre-bound to pane movement, but I want to add Ctrl+Alt+h/l to do Tab movement in normal mode. I already verified that Ctrl+Alt+l has a unique keybind (as expected, it's the Ctrl+l bind modified by escape), so it's frustrating that I can't use it in Zellij.

**Comment by khs26** [comment]
Thanks for raising the issue!

The way zellij handles keybind is using termion's code to map bytes on terminal stdin to keypresses. Some keypresses aren't available via termion, either because they're just missing, or because of the trickier issue that VT100-compatible terminal emulators can't send them through to the [ptys](https://github.com/zellij-org/zellij/blob/main/docs/TERMINOLOGY.md#pty).

We're still in the process of working out exactly what set of characters is generally available to zellij, but I think @imsnif may have already ruled out `Ctrl+Alt+<key>` as a set of characters that lacks a unique representation on the terminal.

**Comment by khs26** [comment]
Sounds like I'm wrong! :) Thanks for sharing your observations.

We've been thinking about forking and/or moving away from termion as our means of doing bytes -> key press translation. Your input here is a useful datapoint and (if you're interested), you'd be welcome to contribute to the discussion and code.

**Comment by Drugoy** [comment]
This issue and issue #735 seem to be about the same thing. I'd close this one in favor of 735th, because it has more valuable information in the comments.
