### ISSUE TITLE
Address blank lines between tab-line, panes, and status-lines

### ISSUE THREAD

**Issue by rustysys-dev** [zellij-org/zellij#586]
Currently the editor is configured as below

```
TabLine
<blank line>
Panes
<blank line>
StatusLine1
StatusLine2
```

I would like to propose removing the blank lines.

Also it would be nice to toggle status-lines (side note)

I am willing to do the work for this myself, but I cannot find where the `<blank lines>` are being inserted.  If anyone could point me in the right direction...?

**Comment by imsnif** [comment]
I responded on Discord but thought I'd paste my reply here for transparency:

Hey! So this is actually a bit of a hack that is there to disguise a larger issue.
This happens because both the status bar and the tab bar are "panes" too, only we hide their borders. That's the gap you're seeing. The whole pane splitting/resizing logic assumes there's a one row/column gap between panes. So fixing this will require quite a bit of an infrastructure overhaul.
The good news is that I'm about to tackle this as part of developing a different feature (having toggle-able "boxes" around panes that would show the terminal title and count of unread lines in the buffer - maybe some more info) in the next couple of weeks.
If you do want to get your hands dirty working on some feature or bug in Zellij - there's plenty to do! I'd be happy to look for something that would interest you.

**Comment by rustysys-dev** [comment]
I will take a look through the issues and see if there isn't something that catches my eye! and I responded in discord, but I will keep an eye out for this fix :100:

**Comment by a-kenji** [comment]
@rustysys-dev 
I believe that has been addressed in the most recent release!
Please reach out if that is not the case.

**Comment by rustysys-dev** [comment]
@a-kenji thanks!!

**Comment by a-kenji** [comment]
It was @imsnif, who fixed it - I was just the messenger!
