### ISSUE TITLE
copy & paste does not work since zellij 0.14

### ISSUE THREAD

**Issue by fansari** [zellij-org/zellij#671]
I have updated from zellij 0.13 to 0.15 and noticed that I was not able to do any copy and paste anymore.

First I did the installation with cargo then I also tried 

https://github.com/zellij-org/zellij/releases/download/v0.15.0/zellij-x86_64-unknown-linux-musl.tar.gz

which gave the same result.

Trying to paste with mouse click gives either no results or strange sequences like "34;55;33M".

I also tried version 0.14 but it also has this issue.

Version 0.13 is the last without this bug.

I am using PuTTY with Windows 10.

**Comment by imsnif** [comment]
Hey @fansari - thanks for opening the issue. There are some fixes in the next version that we're releasing in a few days that might fix this (though I'm not 100% sure). For now as a workaround, I think you can start Zellij with the "disable-mouse-mode" option: `zellij options --disable-mouse-mode`

If the next version doesn't fix this, I'll want to investigate further and find a specific fix.

**Comment by fansari** [comment]
I can confirm that it works again using the option.

**Comment by papanito** [comment]
same here, if I start `zellij` as mentioned above using the option, all is good

**Comment by imsnif** [comment]
@fansari @papanito - thanks for checking this out.

A little bit about why this happens:
Zellij has recently added mouse support so that you can scroll up inside a pane and change the focused pane with the mouse. In order to do that, it has to "take over" the mouse from the terminal emulator (putty in this case). This will happen with every program that behaves in this way (eg. I just tested with a recent version of tmux with mouse support and it happens there too).

So this is one of those "you can't have your cake and eat it" sort of things. If there is mouse support in Zellij, this issue will happen.

I take it you can still paste normally like in other applications? (eg. if you're on windows using ctrl-v)

**Comment by fansari** [comment]
First of all: this issue does also affect v.016 - but from your explanations it is "by design".

Since I need "copy & paste" all the time this is a "no-go" for my use case.

Ctrl-V does not work - I have also tested Shift-Ctrl-V - this also does not work.

The --disable-mouse-mode option does work but not completely. It works as long I am in my session. When I leave the session 
 and reattach it this copy&paste again does not work.

I tried "zellij attach options --disable-mouse-mode" but this only gives an error message.

**Comment by imsnif** [comment]
@fansari - does `ctrl-v` or `shift-ctrl-v` work inside putty without Zellij?

About the `disable-mouse-mode` after reattaching, that's a very good find. And that's something we can definitely fix. I'll open a separate issue for that.

**Comment by fansari** [comment]
Inside PuTTY you cannot use ctrl-v but "shift-insert" works. But even with this I will need the --disable-mouse-mode option because I also need to be able to copy text from the terminal window.

**Comment by imsnif** [comment]
I understand - I'm just trying to understand what we - Zellij - can actually do about it. :)
It sounds to me like the max we can do is solve #688. Unless there's something else you think can be done about this?

**Comment by fansari** [comment]
One idea could be some ~/.zellij config file where you can store your options (maybe something like this already exists and I don't know it?). This way you don't have to enter your options each time you start zellij.

**Comment by imsnif** [comment]
@fansari - you can try "disable_mouse_mode: true" - but I think in this case it will not work. #688 is a bug and we need to solve it first, I'm afraid.

**Comment by fansari** [comment]
This solves both issues: copy & paste is working with this setting. When I reattach the session it still works.

**Comment by imsnif** [comment]
🤦 - I see!

Okay, then #688 is not as bad as I thought :D Good to hear.

**Comment by NthmAnTi** [comment]
Current behavior in Gnome Terminal, Xfce-Terminal, Tilix with not disabled mouse mode: 
- Marking text gives a message: "Text copied to clipboard", but the marked text is not copied into any buffer I know of. With disabled mouse mode copying works.

A little confusion about the buffers in Linux terminals:
- ctrl-shift-v pastes the contents of the system clipboard.
- shift-insert pastes the contents of the system clipboard, except when the last copy action was from an application started via wine. In that case the clipboard content from before that action is pasted. This seems to be a terminal thing.
- All other applications use shift-insert or ctrl-v to paste the contents of the system clipboard.

So it looks like the mouse-mode-copying in Zellij does not copy at all, or at least not into the correct buffer and for testing PuTTY is a bad choice, because it does not support ctrl-shift-v.

**Comment by a-kenji** [comment]
@NthmAnTi 
Thank you for that detailed investigation!
I am not very familiar with how copying in zellij works, but I can attest that it worked flawlessly since the beginning for me personally. 
I don't know if it is implemented how one would suspect though.
![copying-zellij](https://user-images.githubusercontent.com/65275785/132674870-b92a73a9-2ed7-45c0-8613-354a053f7a97.gif)
![zellij-copy-default-layout](https://user-images.githubusercontent.com/65275785/132675282-95aa714f-aa35-48db-9e6c-3be083120c94.gif)

**Comment by imsnif** [comment]
@NthmAnTi - Zellij copies text to the clipboard by sending the OSC 52 signal to the terminal emulator. The rest is up to it. Gnome terminal intentionally does not support this - what you're saying about xfce-terminal and tilix is new to me. That's unfortunate. For me it works great with Alacritty.

We're working on a workaround for this and discussing it here if you'd like to follow: https://github.com/zellij-org/zellij/issues/627

**Comment by a-kenji** [comment]
Handled in https://github.com/zellij-org/zellij/issues/1018.

**Comment by mpenning** [comment]
I still hit this (bad) bug in zellij 0.33.0.

Workaround: `zellij options --disable-mouse-mode`

**Comment by imsnif** [comment]
@mpenning - I would encourage you to take a look at https://zellij.dev/documentation/faq.html#copy--paste-isnt-working-how-can-i-fix-this - and if it doesn't solve your problem, please either reach out in one of our support channels (Discord/Matrix) or open a dedicated issue. When you comment on old issues that have similar keywords in the title but vastly differing particulars, it causes a lot of extra work to maintainers. We'd be happy to help you out, but let's not bring solved issues from the deeps. Thanks!

**Comment by mpenning** [comment]
@fansari said:
> I am using PuTTY with Windows 10.

@imsnif said:
>  I would encourage you to take a look at...

@imsnif, perhaps you could explain where Windows10 + PuTTY is covered in this hyperlink: https://zellij.dev/documentation/faq.html#copy--paste-isnt-working-how-can-i-fix-this

I have spent too much time blaming other things when in fact zellij was broken and lying.  Why "very broken and lying"?  What else am I supposed to think when I highlight text and zellij responds with: "**Text copied to system clipboard**"

What bug am I supposed to file this under when the OP says: "**I am using PuTTY with Windows 10.**"  That sounds... like exactly what I'm trying... countless zellij releases after this issue was closed in Feb 2022.

**Comment by imsnif** [comment]
I have nothing to add about your issue here @mpenning beyond what I already wrote above.

On a personal note: I suggest that if you want me to spend my free time helping you out with an app I (and others) spent our free time developing and giving you for free - you lower your hostility levels. If this is not acceptable to you, I will heartily invite you not to use Zellij.

I'm not going to engage with you on this thread any longer, and will only do so in the other channels I mentioned if you change your attitude. Good day to you.

**Comment by imsnif** [comment]
Sounds good to me. Kudos on the self reflection :+1:

**Comment by nigelatdas** [comment]
I wonder if this is todo with ubuntu having several clipboards :|

**Comment by suryapandian** [comment]
> @fansari said:
> 
> > I am using PuTTY with Windows 10.
> 
> @imsnif said:
> 
> > I would encourage you to take a look at...
> 
> @imsnif, where is Windows10 + PuTTY is covered in this hyperlink: https://zellij.dev/documentation/faq.html#copy--paste-isnt-working-how-can-i-fix-this
> 
> When I highlight text in version 0.33.0, zellij responds with: "**Text copied to system clipboard**" (however, zellij did not copy to the Windows10 clipboard). Using `zellij options --disable-mouse-mode` I worked around the problem, However, in version 0.33.0 zellij copies to Windows10 clipboard, but does NOT say so on the status line.
> 
> If this is the wrong bug, what copy / paste bug should I file this under? The OP says in this issue: "**I am using PuTTY with Windows 10.**"

Could you please update with what you did to get this working? I also tried the steps in FAQ. I also have the same problem of zellij saying “text copied to system clipboard” but it not copying. However when I disable mouse mode copy works. I use macos. Curious to know if you had this resolved.

Will check in discord, but this issue shows up in google search. So, if this was resolved, posting the solution here might be helpful.

**Comment by jackyliu16** [comment]
Is it capable of adding some kinds of vim shortcuts to help people to select, copy, and paste text without the mouse? Just like some neovim terminal plugins provide?

**Comment by crossedheadx** [comment]
Hi, i've found a workaround for copy issue on x11 session suggested from the FAQ

```copy_command "xclip -i -selection clipboard" // x11```

On the FAQ the option `-i` is missing. Tried on Gnome 43 with Debian 12 both Alacritty/Blackbox inside Helix and other programs.

**Comment by liaoya** [comment]
I use zellij recently. I like it because it has one execute file and I can not use tmux on some servers since it need installation.

I use Windows 10 + Putty also. When I want `select and copy`, I will enter edit mode use `C+s e`.

I have a question, is it possible disable `mouse-mode` on fly with hotkey.

**Comment by Zenuncl** [comment]
> I have a question, is it possible disable mouse-mode on fly with hotkey.

I did it with hotkey
`bind "m" { ToggleMouseMode; }`

I don't know if anyone here experienced this issue:
1. SSH to a remote server, 
2. Use Zellij on the remote server
3. When mouse-mode enabled, copy doesn't work. 

Seems like it's not selecting text properly when in mouse-mode. Even when text looks like selected, it's not copy at all. Not with CMD+C / X or Ctrl + C/X. I tried my config on macOS and Archlinux with either iTerm2 or Alacritty. 

without mouse-mode enabled, copy works fine, select-to-copy also works. But with mouse-mode, copy stop working.

**Comment by llagerlof** [comment]
> Hi, i've found a workaround for copy issue on x11 session suggested from the FAQ
> 
> `copy_command "xclip -i -selection clipboard" // x11`
> 
> On the FAQ the option `-i` is missing. Tried on Gnome 43 with Debian 12 both Alacritty/Blackbox inside Helix and other programs.


Thank you, this worked for me. Selecting with the mouse now copy the selection to the clipboard, as expected.

Adding full instructions to help new **zellij** users who encounter the same problem. :

- Edit the **zellij** config file at `~/.config/zellij/config.kdl`
- If not exists, create it using a feature provided by **zellij** itself:
```
$ mkdir ~/.config/zellij
$ zellij setup --dump-config > ~/.config/zellij/config.kdl
```
- Edit this file and search for `copy_command`
- Uncomment the X11, Wayland or OSX line, depending of your system.
- Reload **zellij**, be happy.

**Comment by cammelspit** [comment]
Can confirm using xclip on Arch works a treat and I can copy and paste all day long now my selecting blocks of text with the mouse which is my preferred method. Anyways, this allows me to switch over to Zellnij entirely now!

**Comment by adagio256** [comment]
Is there any dependencies for clipboard support on Debain 13? For example I have `xclip` installed.

**Comment by hemathkumar-bitcot** [comment]
![image](https://github.com/user-attachments/assets/1802b188-8e76-4e1f-9ce2-c433259fb49f)
copy_command "xclip -selection clipboard" // x11
copy_command "wl-copy"                    // wayland
copy_command "pbcopy"                     // osx


getting the "error using the system clipboard" on Ubuntu 22.04 LTS

**Comment by HaroldArpanet** [comment]
> ![image](https://private-user-images.githubusercontent.com/152936801/376444909-1802b188-8e76-4e1f-9ce2-c433259fb49f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDc5NjEsIm5iZiI6MTczMzU0NzY2MSwicGF0aCI6Ii8xNTI5MzY4MDEvMzc2NDQ0OTA5LTE4MDJiMTg4LThlNzYtNGUxZi05Y2UyLWM0MzMyNTlmYjQ5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwNTAxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGZlOTc4MWQ0ZmQzNGFkYWUzOWYxZmU1ZmJmNzBkZWFlMmI2YzY0MGQ5MzZiMDE4NjE1ZjQyNWJiYzQ0ZmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rS-mAXjlmEe2YBxHaKZrovrjzIjFAE8LktLF2PfLczQ) copy_command "xclip -selection clipboard" // x11 copy_command "wl-copy" // wayland copy_command "pbcopy" // osx
> 
> getting the "error using the system clipboard" on Ubuntu 22.04 LTS


Hello
I had the same issue. On Ubuntu, by default, you are using a gnome-terminal or another thing. Some terminals do not support the OSC 52 signal that Zellij by default uses for copy-pasting events. When you enable the copy_command option in the config you need to install external dependency to fix this error depending on your windowing system Wayland or X11 install external dependency.
I think for Wayland, it is `sudo apt install wl-clipboard` in the ubuntu repository and for x11, it is `sudo apt-get install xclip`.
Be happy :)

**Comment by fansari** [comment]
copy & paste with zellij is really a mess. In my case I use a Windows terminal from there I SSH a Linux VM and there I run zellij.

When I copy more than one line all lines are in copied into a single line.

This is unusable.

**Comment by satyakam-vyrill** [comment]
**Work of this Changes(copy and Paste)**

1) Install xclip if it's not already installed:
  `sudo apt install xclip`

2) Navigate to this file
  `cat .config/zellij/config.kdl`

3) Uncomment the following line
  `copy_command "xclip -selection clipboard"`

**Comment by rulatir** [comment]
> I still hit this (bad) bug in zellij 0.33.0 / Windows10 / PuTTY v0.78
> 
> Workaround: start zellij with: `zellij options --disable-mouse-mode`

What otherwise potentially desirable functionality is jettisoned by `--disable-mouse-mode`?
