### ISSUE TITLE
Pane frame shifts on certain input titles.

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#689]
The pane frame can shift, if certain characters are in the title.

Version: `0.17.0`

To reproduce:
* Put a `❄` character in the title.

![image](https://user-images.githubusercontent.com/65275785/132062004-a1ea3897-4420-4d56-84e6-f6745380e843.png)

**Comment by imsnif** [comment]
@a-kenji I fixes this in main, could you please confirm?

**Comment by a-kenji** [comment]
@imsnif
This fixes the issue for me, cheers!

**Comment by a-kenji** [comment]
@imsnif 
As mentioned in the other issue, it still sadly happens for me in kitty:
![image](https://user-images.githubusercontent.com/65275785/132254838-f2e7e486-5a77-46ee-9c2f-53f24edc03f4.png)
If I can send you any more information that would help, please say so!

**Comment by imsnif** [comment]
@a-kenji - I think this is either a bug in kitty or in unicode-width. I suspect the latter but am not 100% sure. I opened an upstream issue: https://github.com/unicode-rs/unicode-width/issues/22

Are there any other characters you found this issue with?

**Comment by a-kenji** [comment]
No, not yet. But this is the only one I really tried now.
I will check other default starship ones.

**Comment by imsnif** [comment]
@a-kenji - so the upstream issue in unicode-width was my mistake. This is actually an issue with Kitty: https://github.com/kovidgoyal/kitty/issues/2929 (though according to Kitty, it's an issue with everyone else :D ).

Kitty is generally hostile to terminal multiplexers (https://github.com/kovidgoyal/kitty/issues/391#issuecomment-638320745), so I personally don't really want to engage with them in order to try and solve this issue. I'm afraid my recommendation to anyone who is affected by this issue is the inverse of Kitty's recommendation about terminal multiplexers: don't use Kitty.

If a Kitty maintainer is reading this and would like to resolve this issue amicably in a way that would benefit both our user-bases, I'd be very happy to do so.

**Comment by a-kenji** [comment]
@imsnif 
Thanks for taking a look again, I guess I need to avoid those characters in kitty.
Just for reference:

* Alacritty:
![image](https://user-images.githubusercontent.com/65275785/132348522-10b0ea74-fa4f-418e-87a7-b02f05998457.png)
* Kitty:
![image](https://user-images.githubusercontent.com/65275785/132348663-ad097c4b-2063-47fa-9264-6f33e53b3ab5.png)

**Comment by greneholt** [comment]
It turns out this actually was a bug in unicode-width, it just took them several years to fix it (https://github.com/unicode-rs/unicode-width/pull/41). If zellij upgrades to unicode-width v0.1.12 this issue should be resolved.
