### ISSUE TITLE
Could not find the SHELL variable: NotPresent

### ISSUE THREAD

**Issue by XFFXFF** [zellij-org/zellij#700]
**Basic information**

`zellij --version`:  0.16.0
`tput lines`: 52
`tput cols`: 211
`uname -av` or `ver`(Windows): Linux 5.0.9-1.el7.elrepo.x86_64 #1 SMP Sat Apr 20 09:03:57 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/30254428/132281084-a6306c9c-31de-404d-b295-5ddc72dcc1c0.png)

**Comment by imsnif** [comment]
Hey @XFFXFF - sorry about the experience!

The $SHELL variable is how we find out what your default shell is in order to open new terminals. I'm not sure why it's not defined  on your machine (I guess `echo $SHELL` is blank for you?)

A workaround can be to either set that variable permanently (with something like `export SHELL=/bin/bash`) or to start Zellij by explicitly specifying your shell with: `zellij options --default-shell /bin/bash` (or whichever shell you'd like to specify).

**Comment by XFFXFF** [comment]
@imsnif  `echo $SHELL` does not return empty
![image](https://user-images.githubusercontent.com/30254428/132320007-b645a798-7d01-4434-9466-37d4ac7bf6d0.png)
But `zellij options --default-shell /bin/bash` works for me.

**Comment by XFFXFF** [comment]
@imsnif  It's very strange that when I set the environment variable ( export SHELL=/bin/bash), zellij can work normally again
![image](https://user-images.githubusercontent.com/30254428/132320585-1d301278-b559-4e5f-99bc-ed75789a766c.png)

**Comment by XFFXFF** [comment]
@imsnif My problem is solved, should I close the issue?

**Comment by a-kenji** [comment]
@XFFXFF,
If you don't mind, it would be awesome if you documented how
your issue was fixed - for anyone experiencing a similar problem.

But yes if it is fixed you should close it.

Thanks for reaching out and please don't hesitate contacting us again!

**Comment by XFFXFF** [comment]
I fixed it by manually setting the environment variable `export SHELL=/bin/bash`, and start Zellij by explicitly specifying the shell can also work (`zellij options --default-shell /bin/bash`)
