### ISSUE TITLE
Ability to name tabs from the config file

### ISSUE THREAD

**Issue by stratosgear** [zellij-org/zellij#706]
After looking around (and consulting in the discord channel) it seems there is no way to name your tabs from the config file (you can only name them manually, from a running instance).

I think there **ought** to be a way to do that from the config file, too!

**Comment by a-kenji** [comment]
Thank you for taking the time writing down this issue.

For anyone that wants to pick this up: 
I think it would only make sense to have them be named in the layout file, as opposed to the config file for now.

**Comment by stratosgear** [comment]
Yes, I meant the layout file (sorry for messing up the terminology)

**Comment by tw4452852** [comment]
I can help on this

**Comment by a-kenji** [comment]
That would be awesome! @tw4452852

**Comment by a-kenji** [comment]
@stratosgear 
No problem, this is very valuable!

**Comment by prscoelho** [comment]
Hey guys, since I recently made a PR for tab-bar, my mind is still fresh on this and I have some questions.

Will control characters be allowed in the tab name from layout file? And can we prevent that easily? Currently an unescaped \n or \t will completely mess up the spacing count and rendering, but I don't know if we care at all, it's deliberate bad input and it doesn't result in a panic, just a bad result from bad input.

And since any kind of characters will be allowed into tab name I guess we should probably change the width count from chars().count() to unicode-width. I can make a PR for that.

**Comment by a-kenji** [comment]
@prscoelho 
Thanks for raising these issues! 
I am all for the tab width pr.
I am not too sure about the escaping one. Maybe open an issue? At some point templating for configured strings make sense maybe. So we can keep that for collecting ideas.
