### ISSUE TITLE
feature: pane synchronize and etc

### ISSUE THREAD

**Issue by trankchung** [zellij-org/zellij#712]
Features request

- Synchronize typing: ability to type to all panes at once
- Hide/show action menu at the bottom
- Hide/show pane title
- Rename tabs
- Rearrange tabs
- Move tab/action menus to top/bottom

**Comment by a-kenji** [comment]
Hello! Thank you for taking the time creating this issue!
Some of these things are actually implemented in the default config:
* rename tabs -> tab mode -> r -> rename -> enter
* hide/show/pane title -> pane mode -> z (it toggles the pane frames, I think that is what you meant?)
* synchronize -> tab mode -> s -> type in a pane and all panes in the tab are synchronized

> Hide/show action menu at the bottom
I think we have an issue for toggling the viewport already.

> Move tab/action menus to top/bottom
You can do this by using the layout template system:  https://zellij.dev/documentation/layouts-templates.html .

**Comment by trankchung** [comment]
The hide pane title means I want to hide the text, still want the box to display. Another option would be to rename the pane title.

**Comment by a-kenji** [comment]
Ah yes, configuration of the pane in general is also already an issue #680, but you can already hide the text,
except for the scroll notification. 

![hello-zellij](https://user-images.githubusercontent.com/65275785/133003585-0e3b713f-1cd9-43be-affb-79ea416790a1.gif)
For example here I hide most of my shell prompt on entering zellij and then
I will show it in the pane frame.

But it is also possible to rename the text, for some reason there sadly is still some space left, I think this might be a bug:
![image](https://user-images.githubusercontent.com/65275785/133003727-04cb55b2-5d53-4398-b1be-9ea1c7924d44.png)

The title of the pane is the title that your shell provides, so depending on the shell
if you configure it, it will be different. It is planned though to make it more configurable
in the future.

**Comment by a-kenji** [comment]
@trankchung 
I will close this issue, as I think your questions have been answered?
If that is not the case please reply!

And please don't hesitate reaching out in the future for further issues, or questions!

**Comment by chungktran** [comment]
@a-kenji Can you point me to where I can rename the panes and/or move the tabs to the bottom? Aso, how do I hide the CTRL+ menu items? Thanks.

**Comment by a-kenji** [comment]
@chungktran 
Sure!

* I moved the tab bar to the bottom with changing my default layout:
```
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      body: true
    - direction: Vertical
      split_size:
        Fixed: 1
      run:
        plugin:
          path: tab-bar
      borderless: true
```
Also I didn't hide the status bar at the bottom, I didn't load it in the first place.
We are still working on toggling stuff outside of the viewport.

* Renaming panes:

That depends on the shell you are using.
If the pane shows a title on the top left side, then the shell you are using
is sending the instructions on the title to zellij. I think you can configure each 
shell to show the title.

I personally am using the fish shell currently, so I am modifying the `fish_title`
function and anything this function emits will be picked up and shown by the title,
if I set the function to send an empty string, then the 2nd picture I sent will be shown,
otherwise the first picture will be shown, because I set the prompt from the `starship`
as my title.

**Comment by a-kenji** [comment]
@chungktran 
Here is a link to the layout documentation: https://zellij.dev/documentation/layouts.html .
