### ISSUE TITLE
Weechat rendering issues

### ISSUE THREAD

**Issue by auronandace** [zellij-org/zellij#761]
`zellij --version`: zellij 0.18.1
`tput lines`: 64
`tput cols`: 271
`uname -av`: Linux silentpc 5.13.19_1 #1 SMP Sat Sep 18 18:18:26 UTC 2021 x86_64 GNU/Linux
`alacritty --version`: alacritty 0.9.0
`weechat --version`: 3.3

When using weechat inside zellij there are some rendering issues that start to occur over time.

1. Some of the nicks in the nicklist on the right appear misaligned either further to the right or further to the left.
2. The blue status bar just above where you type doesn't go all the way to the right after you have seen some of the notifications by switching channels.

I suspect these may be redrawing issues. Sometimes if I toggle panes on or off it forces a redraw and everything looks the way it should.

**Comment by imsnif** [comment]
Hey @auronandace - thanks for opening the issue. It might be fixed in the next version (we fixed some issues with re-rendering while scrolled) - but it would be very hard to know and reproduce without some logs. Do you think you can attach some logs of this happening as mentioned here: https://github.com/zellij-org/zellij/blob/main/.github/ISSUE_TEMPLATE/bug_report.md ?

Thanks!

**Comment by auronandace** [comment]
The status bar issue is super easy to reproduce.

- Launch weechat in a zellij session and connect to a server
- /join serveral channels and wait for people to join/part or speak in them
- switch between the channels that have had activity

You'll see the bar decrease in size as the notifications are cleared from the status bar.

The first issue I've been trying to reproduce for the last few hours but it takes some time. I'm not entirely sure what exactly causes the mis-alignment. Maybe different length nicks joining or speaking that alter the size of either the nicklist or the text window.

**Comment by imsnif** [comment]
The might be - but as a person who doesn't use weechat, I'd have to install it and probably go through some setup and figuring out eg. channels in order to reproduce this bug - not to mention that if it takes me time to get it, the version might be different and for whatever reason I won't be able to reproduce it.

We ask you to add the logs (and provide the tput lines/cols of the pane from which the logs were taken) to facilitate the cognitive load of the person who wants to solve the bug. It's not a must, but it'll be much easier for us if you do.

**Comment by auronandace** [comment]
Like I said, it is taking time to reproduce. When it happens I'll gladly give you the logs.

**Comment by auronandace** [comment]
Finally happened. I quit as soon as the mis-alignment happened. There was only the one pane and just weechat running inside zellij.

[zellij.log](https://github.com/zellij-org/zellij/files/7273454/zellij.log)
[zellij-11.log](https://github.com/zellij-org/zellij/files/7273455/zellij-11.log)

**Comment by imsnif** [comment]
Awesome, thanks for making this effort! I'll try to take a look in the near future. Are the tput lines/cols you mentioned above correct to this one pane? I'll need them in order to reproduce it with the logs correctly.

**Comment by auronandace** [comment]
Should I have run that inside the zellij session or is it just to match the size of the entire terminal?

I'm running i3 so those tput figures are for an empty terminal on a virtual desktop with nothing else. Which is the same as the setup for reproducing the issue (1 alacritty terminal, nothing else open, weechat in zellij).

**Comment by imsnif** [comment]
It's the second figure, yeah. We need the size of the pane.

I reproduce these sorts of issues by `cat`ing the log file (`zellij-11.log` in this case) inside a terminal of the same size as the one that created it (the Zellij pane in our case, which is its own "mini-terminal"). Doing that, I'm able to see on my screen exactly what you saw on yours when you quit Zellij. I compare it with how it looks outside Zellij in a terminal of the same size and go from there.

**Comment by auronandace** [comment]
I think the misalignment might be occuring due to the emoji font.

`fc-match Emoji`: NotoColorEmoji.ttf: "Noto Color Emoji" "Regular"

Whereas the font I have set up for normal text in alacritty is: FiraCode-Regular.ttf: "Fira Code" "Regular"

**Comment by auronandace** [comment]
I believe #964 and #965 fixes the alignment issues.

The only issue left now is the staus bar reduction. This is really a minor issue that is only asthetic in nature so I'll close this issue.
