### ISSUE TITLE
Flakey Scrolling Issue

### ISSUE THREAD

**Issue by markus-wa** [zellij-org/zellij#797]
Video of the bug:
https://user-images.githubusercontent.com/5138316/138323913-ee4e48ae-9d7c-408a-a0b6-92aa87b524f3.mp4

I keep randomly getting the scrolling issue in the attached video at the bottom. Basically after some large outputs the scrolling stops working properly and it skips a huge chunk of output.

In the video I use my cursor to mark the gap in output - you can see the git status from my earlier command is just cut off in the middle.

Note that it seems to cut off at `tput lines` right after the issue happens but after resizing or running additional command scrolling still just cuts off at the same lines (i.e. not at the resized `tput lines`)

**In Case of Graphical or Performance Issues**

I don't know how to reproduce this bug exactly, but it keeps happening to me every day
If I manage to get the debug info I will attach it afterwards

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: `zellij 0.19.0`
`tput lines`: 28 / 71
`tput cols`: 86 / 282
`uname -av`: `Linux mark-ThinkPad-X1-Extreme-2nd 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`alacritty --version`: `alacritty 0.9.0`
`zsh --version`: `zsh 5.8 (x86_64-ubuntu-linux-gnu)`

**Further information**
I'm not sure how to reproduce it

Thanks for making Zellij :heart:

**Comment by raphCode** [comment]
I also hit this bug occasionally without any clue on what it might cause.

Can we record the terminal session with `script` until we hit the bug and then try to replay it?

How can we start a `script` session in each pane opened?
I naively tried `SHELL=script zellij` and `zellij options --default-shell script` and it didn't work...

**Comment by jovandeginste** [comment]
Am I the only one just not having a useful scroll-buffer in Zellij? I have to resort to `| less` for everything if I want to see more than what's on the screen.

If the issue is non-reproducibility, look no further :-)

**Comment by imsnif** [comment]
> If the issue is non-reproducibility, look no further :-)

I am very eager to find a way to reproduce this! Are you experiencing the same issue as OP? Losing some lines when scrolling up? Can you reproduce it every time?

**Comment by jovandeginste** [comment]
I have an actual case of it; I can not reproduce from zero, but I have a zellij "instance" running, and when I attach to it, I can not scroll all panes.

While I was testing, I noticed it was mostly the top panes...

Since I'm not sure what exactly causes it, here are some details:

- it happens very frequent, to the extent that I was under the impression that the scroll feature was still in alpha
- I (re)use my tabs & panes constantly, but I do often close some (by accident)
- the session I'm attached to now, has 3 tabs
  - the second tab has 4 panes in a 2x2
  - in that tab, only the pane left-bottom has working scroll at this moment
  - all other panes in the other tabs seem to have working scroll ....
- it seems unrelated to my (bash) prompt - I started a vanilla "sh" and still scroll is broken where it was broken before

I'm up for making a screen recording, however the shells will probably contain some sensitive information. Therefore, I will certainly not post it here. Also, I'm unsure about the value. Maybe I can enable debug logging? Can I do that to a session that was already created?

**Comment by imsnif** [comment]
Hey @jovandeginste - thanks for all the details!

While always possible, it's unlikely that this happens due to anything outside a specific pane (save for resizes that affect the pane with the scroll, but those can be replicated by resizing the terminal window as well).

The best way for me to debug this would be to get the debug log from a specific pane (the output you get when you start zellij with `--debug` - there are detailed instructions where to find it in our ISSUE_TEMPLATE).

If you can find a few steps that you can use to reproduce this in one pane and then send me its log (you can do so privately to aram@poor.dev if you like) that would be very helpful for debugging this. Try to make the log as succinct as possible if you can. As in - if you find a way to reproduce this consistently, try to close Zellij, restart it with `--debug`, reproduce this and then exit immediately and send the created log.

It's also important to note that the log file is appended to on each Zellij restart, so might be a good idea to delete it before if you made several attempts. Also be sure to log the pane's columns/rows so I can reproduce it with the same size pane (I essentially just `cat` the log file into a pane and then I can see all the pane's scrollbuffer and should be able to reproduce this).

**Comment by imsnif** [comment]
To reiterate: this is very likely caused by some output inside the terminal pane itself. For example: some specific command moves the cursor to somewhere in a way that we don't handle correctly and this starts everything.

**Comment by jovandeginste** [comment]
It's certainly possible - I sometimes cat a binary file by accident (or on purpose).
I made a screen recording of the scroll issue itself, but this won't help much. I'll kill my session and restart with `--debug`.

**Comment by jovandeginste** [comment]
Last night I tried to make it happen without success; I disconnected the session, and went to sleep. Today, I start working, attach the session, and lo-and-behold: the issue, immediately!

The log file of the pane with the issue however is about 12MB and certainly contains sensitive data. I also have no idea how to exactly proceed here, since there is so much in the log file (including vim sessions)

**Comment by imsnif** [comment]
Hrm... yeah - this issue is certainly quite tricky! It'll also be very hard for me to debug this and find the specific instruction that causes this with such a big log file.

Could it be the reattaching itself perhaps that plays a role here somehow?

**Comment by jovandeginste** [comment]
Oh, I just found a way to reproduce it in a few seconds!

- open zellij
- fill your screen until you can scroll up
- start `watch -n1 date`
- wait a few seconds
- hit ctrl+c
- scroll misses a few lines

**Comment by jovandeginste** [comment]
(I did not detach/reattach, FWIW, just started `zellij` (0.20.1) with no extra flags. I do have mouse input & pane borders disabled and some custom key bindings.

**Comment by jovandeginste** [comment]
in fact, now I'm testing more, and scroll seems to stop at the last scroll-position. Scrolling up always shows the same line as first in the scroll buffer (I hope I'm making sense to you ...). It's as if nothing new is being added to the scroll buffer anymore.

**Comment by imsnif** [comment]
YES!! I AM REPRODUCE THIS! :D :D

And yeah, you're right. That definitely seems like the issue. I'm going to play with this some more and hopefully issue a fix soon.

**Comment by jovandeginste** [comment]
However,  I'm not sure this is exactly the issue @markus-wa is facing too.

**Comment by jovandeginste** [comment]
Thank you!

**Comment by mhristache** [comment]
I am still getting this issue with zellij 0.40.1, not sure what the trigger is but I mainly get into it when using ssh sessions (zellij running on my machine from which I ssh to other machines). `reset` is fixing it, `echo -e "\033[r"` doesn't
