### ISSUE TITLE
Add Multiple Tips To Zellij

### ISSUE THREAD

**Issue by TheLostLambda** [zellij-org/zellij#808]
Currently we just have a single "tip" that shows up in the Zellij status-bar – it would be nice to add a list of tips that are semi-randomly selected (a Did you know? style bit of information)

We should add the fact that `SHIFT` bypasses mouse-capture at run-time!

**Comment by jaeheonji** [comment]
I think this is quite good feature. I've been looking for a function or use-case similar to this, but most seem to randomly display "tips" when the program is run. And "tips" data is mainly provided in two ways.

* From an external server ([oh-my-zsh/themes/adben.zsh-theme](https://github.com/ohmyzsh/ohmyzsh/blob/55682e36920e2ab7633fc6eee11466d3faed0bf8/themes/adben.zsh-theme#L77))
* Hard corded in source ([iterm2/sources/iTermTipData.m](https://github.com/gnachman/iTerm2/blob/4e8ea9aa730d7bb1a23d62b20701a5f03e878c0a/sources/iTermTipData.m#L14))

Of course, it is also possible to show tips at regular intervals internally in the system (like `cron`)
At this point, personally, it seems good to create a tips data file and display it randomly every time the program starts.

**Comment by imsnif** [comment]
Hey @jaeheonji - I generally agree. I think for us, since we don't intend to display a large number of them, it would be totally fine to have them hard-coded in the source in a separate data file.

I think your idea of having them displayed on startup is good. I find it important though that the current tip be displayed the first 10 times the user opens the app. So we might also want to keep a cache file to track that.

**Comment by a-kenji** [comment]
@jaeheonji 
If it is possible I would also say have this file in the `status-bar` for now,
since that is the only place we currently would be able to display the tips.

**Comment by jaeheonji** [comment]
After looking at `status-bar/second_line.rs`, I thought of two ways:

* Like `fn quicknav_full` and `fn quicknav_medium`, write a function for the new tip.
   but bascically, since the length of each function is large, it is necessary to separate the files.
* Create a HashMap (or any other data structure) with information such as `text` and `color`, and create a new function to create a `LinePart` from it.

My personal opinion, latter looks good because of scalability and reliability. What do you guys think!?

**Comment by imsnif** [comment]
Hey @jaeheonji - I think it'll be easier to discuss these in a PR. Go ahead and do what you think is right, worst case we'll discuss it abit and suggest some changes. Would be really cool if you pick this up.

**Comment by jaeheonji** [comment]
@imsnif Ok! good, I'll make a PR with draft :)
