### ISSUE TITLE
Suggestion: Awesome Zellij Plugins

### ISSUE THREAD

**Issue by fedoranvar** [zellij-org/zellij#878]
Good day to you!

I'm thinking about writing plugins for zellij and some examples will be good help with that and for inspiration.
Maybe create some paragraph in docs for collection of user-plugins?

Like:
https://github.com/rockerBOO/awesome-neovim
https://github.com/rothgar/awesome-tmux

etc. 

Thank you!

**Comment by imsnif** [comment]
cc @TheLostLambda

**Comment by a-kenji** [comment]
@fedoranvar 
Thank you, this is an awesome suggestion!
I have added a section to the [documentation](https://zellij.dev/documentation/plugin-overview.html),
since I think having everything in one place for now makes sense.

Once the list gets bigger we could maybe add categories,
or even make a separate list just for it.
