### ISSUE TITLE
Feature(mode): add reset counter for modes

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#891]
Why is there no reset counter for the mode (ideally indicating that it requires configuration so be like 3 seconds or longer)?

_Originally posted by @matu3ba in https://github.com/zellij-org/zellij/issues/307#issuecomment-825622323_

Maybe something to consider?
Needs more discussion.

**Comment by matu3ba** [comment]
@a-kenji tmux configurations typically use `C-a` or `C-b` and wait for 3 seconds (but this can be configured) to insert actions.
This can be useful, when you are done resizing and you can go directly to another window without needing to press enter etc.
But retrospecitvely I think it is more of an anti-feature of tmux.

What I am mostly still struggling is the idea of mapping both `<C-anykey>` and `<Alt-anykey>` and having on top this mode system. I dont understand how fixed modes are faster than (doing it like kakoune and helix) describe the action and show
intermediate states. The other annoyance is that the default keybindings are not memorable.

`g` for lock, `n` for resize, `h` for move, `o` for session are only a few examples due to a messed up prefix `C-` and `Alt-`.
If you compare it to kitty, most stuff is prefixed with `C-Shift-anykey(s)`.
Wezterm [even offers no default setting](https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivatePaneDirection.html?highlight=ActivatePaneDirection#activatepanedirection).
In vim you have the prefix `C-w` for window actions and at least memorable defaults.

So personally I like to have default bindings that help me memorize the terminology of the program,
before I rename them to something more efficient and attach a comment behind so I have a better way to remember it.

**Comment by a-kenji** [comment]
Hey! Thanks for taking the time answering this!

> What I am mostly still struggling is the idea of mapping both <C-anykey> and <Alt-anykey> and having on top this mode system. I dont understand how fixed modes are faster than (doing it like kakoune and helix) describe the action and show
intermediate states (if needed).

I think we want to ultimately be ready to show contextual information similar to kakoune and helix. 
This is a good point, but this is exactly why I think the modular system shines. Because this is possible.

> The other annoyance is that the default keybindings are not memorable.
> g for lock, n for resize, h for move, o for session are only a few examples due to a messed up prefix C- and Alt-.

Yeah, that is sadly a problem. That is kind of why the status-bar is there I feel.


> I dont know how and why the decision for a leader key in zellij was abandoned.

It is not really abandoned. The modal nature makes it very easy to add a leader/prefix key experience,
it is just not bound that way as a default.
There is an [example](https://zellij.dev/documentation/keybindings-examples.html#prefix-example) configuration in the documentation.

I personally use a configuration very closely matching the example configuration.
I probably will update the configuration in the example shortly a little.

**Comment by matu3ba** [comment]
Hey @a-kenji, see #962 for a simplified example that still provides most of the functionality besides nice-to have stuff like renaming panes and windows.

Best thing: It has memorable keybindings. Less good: It "blocks" the Alt key, which is only not utilized by vanilla (neo)vim but alont other editors. Less good fix: Requires more advanced keybindings system that allows multiple keys.

I do experience quite some crashes only on the wasm side and disabling the wasm stuff somehow doesnt work for me.
The non-wasm stuff just works.

**Comment by a-kenji** [comment]
I'm closing this for now, since the actual use case seems to be solved.
I am OK with opening this again if someone has a use case for this.
