### ISSUE TITLE
Equivalent to tmux zoom feature

### ISSUE THREAD

**Issue by DanCardin** [zellij-org/zellij#968]
One of the few behaviors I use in tmux today (that i can tell) which would prevent me from using zellij over tmux

I notice the zoom feature is listed in the set of currently unsupported features, and is commented out in the tmux compatibility config. So I realize you're aware that it's not supported.

Thus, this issue is just registering my desire for the feature.

Some potential design questions (or as options) are:
* should pane navigation work while the panel is zoomed? (tmux behavior says yes, i think it makes sense as an option)
* should you stay zoomed? (tmux **default** behavior says no, although apparently they added a -Z option to `select-pane` which enables the ability to stay zoomed)

Note, this feature has the potential to interact with https://github.com/zellij-org/zellij/issues/967. My current tmux behavior is that tmux panes will navigate while zoomed (and unzoom me), but if vim is focused (and has splits) and the pane is zoomed, then pane navigation is disabled and only splits will be navigated

**Comment by jaeheonji** [comment]
`Zellij` already has a `fullscreen` feature similar to the zoom mode. it can be used by `<C-p> + f`. but, unlike tmux, pane navigation is limited in fullscreen mode. I agree that It would be nice to have the ability to navigation the pane even in full screen mode.

**Comment by imsnif** [comment]
Hey, I second @jaeheonji - I think the fullscreen feature is what you're looking for. Can we close this @DanCardin, or did we misunderstand you?

**Comment by DanCardin** [comment]
fullscreen **does** seem equivalent to zoom. I'd argue the lack of ability to navigate amongst panes while fullscreen (either being shunted out of fullscreen or just switching panes and staying fullscreen) are features I'd want to call it equivalent to tmux's zoom.

I suppose the modal nature of (at least default) zellij's keybinds perhaps makes it less of an issue than it might have been in tmux, if you're already in pane-mode. a quick `fl` does the trick.

but compared to today with tmux if i'm, say, doing stuff in vim (and with my https://github.com/zellij-org/zellij/issues/967 setup), i can do `<c-l>` inside vim inside zoom to switch panes. versus in zellij `<c-p>fl<c-p>`

**Comment by imsnif** [comment]
That's fair @DanCardin. Maybe once we solve #967  we can revisit this? I plan on doing some revamping to the default keybindings which I hope will make things more comfortable.

**Comment by jaeheonji** [comment]
I think that we only have to focus the migration from tmux zoom to zellij fullscreen in this issue.
As far as I know, The difference from tmux zoom mode is that Zellij cannot navigate to the hidden pane when fullscreen.

As @imsnif mentioned, the default keybinding will become more comfortable. Therefore, It seems better to consider keybinding later.

And, I agree that this feature is also potentially related to #967.

But, since there are many requirements for seamless navigation (the main topic of #967), I think it will be helpful to proceed with the task only by considering migration in this issue.

**Comment by DanCardin** [comment]
>  As far as I know, The difference from tmux zoom mode is that Zellij cannot navigate to the hidden pane when fullscreen.

exactly yes. I'm not at all concerned about the default keybind. With the ability to navigate to the hidden panes from inside fullscreen would be technically equivalent to tmux zoom.

**Comment by raphCode** [comment]
It has been a while since the discussion.

As far as I understand the request, navigation between panes is now possible?
I tested it like this with default keybinds:
- open zellij
- open new pane `Alt-n`
- make pane fullscreen `Ctrl-p` `f`
- switch panes with `Alt-h`/`Alt-l` or with `Ctrl-p` `left`/`right`

If I am correct we may close this?

**Comment by imsnif** [comment]
This was implemented, yes. Closing - thanks @raphCode !
